feat/SOV-450
DistributedCollective/sovryn-dapp pull request #10
Opened 2022-09-12 10:42 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-450

2022-09-14 11:56 UTC, creed-victor approved these changes

2022-09-14 13:44 UTC, tiltom requested changes

2022-09-14 13:44 UTC, tiltom commented on packages/ui/src/1_atoms/Icon/Icon.tsx
> +        data-icon={icon}
I know it's not specifically mentioned in the description but we had a discussion with @soulBit and we want to have `data-action-id` in all of the components so pls add it to this component as well (take a look at `Input` and `InputBase` in https://github.com/DistributedCollective/sovryn-dapp/pull/8 ).

2022-09-14 13:44 UTC, tiltom commented on packages/ui/src/1_atoms/Icon/icon.test.jsx
> +  //render icon from the Fontawesome library
We don't need these kinds of comments, the test names should be descriptive enough. Pls delete them.

2022-09-14 13:44 UTC, tiltom commented on packages/ui/src/1_atoms/Icon/icon.test.jsx
> +  test('render fa icon', () => {
```suggestion
  test('renders an fa icon', () => {
```

2022-09-14 13:44 UTC, tiltom commented on packages/ui/src/1_atoms/Icon/icon.test.jsx
> +  test('render custom icon', () => {
```suggestion
  test('renders a custom icon', () => {
```

2022-09-14 13:44 UTC, tiltom commented on packages/ui/src/1_atoms/Icon/icon.test.jsx
> +  test('render icon from Sovryn Library', () => {
```suggestion
  test('renders an icon from Sovryn Library', () => {
```

2022-09-15 08:19 UTC, tiltom requested changes

2022-09-15 08:19 UTC, tiltom commented on packages/ui/src/1_atoms/Icon/Icon.tsx
> +        data-action-id={dataActionId}
You have a missing dependency in `renderIcon`.

2022-09-15 10:19 UTC, tiltom approved these changes

2022-09-19 08:23 UTC, merged