feat: add getTokenInfoByAddress
DistributedCollective/sovryn-dapp pull request #105
Opened 2022-11-28 10:53 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-1087

2022-11-28 15:46 UTC, tiltom requested changes, later dismissed

2022-11-28 15:46 UTC, tiltom commented on packages/contracts/src/utils/global.ts
> +export const getTokenInfoByAddress = async (
I think you should do it the same way I told you before - to unify existing `getTokenDetailsData` function with the new one and use `address` as a parameter for the new function and `tokenName and chainId` for the current function.

I'd prefer not to obtain only `TokenBaseInfo` because if you return the `TokenDetailsData` instead, you'll cover all of the possible use cases we may have in the future.

2022-11-28 15:46 UTC, tiltom commented on packages/contracts/src/utils/getters.ts
> +export const getTokenInfo = async (
```suggestion
export const getTokenDetailsByAddress = async (
```

2022-11-28 15:46 UTC, tiltom commented on apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
> +    //eslint-disable-next-line
Why?

2022-11-29 11:42 UTC, soulBit approved these changes
Verified review comments have been addressed, and made two small fixes (already discussed with Rick)

2022-11-29 11:43 UTC, merged