Zero: LOC getting started popup
DistributedCollective/sovryn-dapp pull request #117
Opened 2022-12-06 09:03 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1090

2022-12-06 14:00 UTC, tiltom requested changes

2022-12-06 14:00 UTC, tiltom commented on .changeset/tiny-seas-approve.md
> +Zero: LOC getting started popup
```suggestion
SOV-1090: Zero - LOC getting started popup
```

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/2_molecules/DebugContent.tsx
> +              <p>Placeholder for ZERO LOC transaction dialog</p>
Why you just don't show `GettingStartedPopup`? I don't understand why is this necessary and I don't see it in the requirements either.

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.module.css
> +    @apply leading-5;
I don't think this is correct, one advantage of a UI components library is that we have a set of components ready to use and since you use `Heading` component, it should use `line-height` defined there. Consult it with Gilad if you can use default `line-height` from `Heading` instead.

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.module.css
> +  & > h1 {
```suggestion
  .title {
```
I don't like this approach, the naming should be descriptive and not just a copy of the current CSS structure. If we decide in the future to change `h1` and `h2` to `h3` and `h4`, styles would just stop working and I can imagine it wouldn't be a pleasant debugging.

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.module.css
> +  & > h2 {
```suggestion
  .description {
```

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.module.css
> +  }
The exact same comments I had regarding `title` and `description`.

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.module.css
> +.box {
```suggestion
.itemWrapper {
```

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.module.css
> +.boxContent {
```suggestion
.texts {
```

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.tsx
> +const DEFAULT_PAGE_SIZE = 1;
```suggestion
const pageSize = 1;
```
You don't offer any option to override `pageSize` so the naming is a bit misleading. Also, it's not a global constant but a local one so I think that camelCase should be fine (but it can be `PAGE_SIZE` if you agree on that with @soulBit).

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.tsx
> +  const [isOpen, setIsOpen] = useState(false);
I think you should have 2 props - `isOpen` and `onConfirm` and it's not something that should be in the component itself.

2022-12-06 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.tsx
> +      reactLocalStorage.set('gettingStartedPopup', 'false');
Extract `gettingStartedPopup` to a variable (e.g. `localStorageKey`) and use that instead.

2022-12-06 14:18 UTC, pietro-maximoff commented on apps/frontend/src/app/2_molecules/DebugContent.tsx
> +              <p>Placeholder for ZERO LOC transaction dialog</p>
it's just for example, and its not necessary

2022-12-06 14:32 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.module.css
> +    @apply leading-5;
confirmed with Gilad

2022-12-06 15:12 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.tsx
> +  const [isOpen, setIsOpen] = useState(false);
@tiltom i'm not sure about it, because it wasn't in the specs and if i will have these props, then i probably should move the logic with localStorage outside of the component as well, because if i send for example "true" in the isOpen prop and then inside the component, i detect that i have localStorageKey - it means that i shouldn't show it - it won't make any sense) but if you think that we strongly should have these props, then pls describe in more detail what logic we should have here

2022-12-06 15:31 UTC, tiltom commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.tsx
> +  const [isOpen, setIsOpen] = useState(false);
I think that you wouldn't need to move the local storage logic outside the component - you would just check in an `effect` if `isOpen` is `true` and `localStorageKey` exists and if so, you would call `onConfirm` (which will set `isOpen` to `false` in a parent component). Or do you think it won't work that way?

2022-12-06 16:30 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.tsx
> +  const [isOpen, setIsOpen] = useState(false);
@tiltom i managed it to work in this way, you can check and I replaced `useEffect` with `useLayoutEfect`, because with `useEffect` this dialog blinked before hiding

2022-12-07 09:45 UTC, tiltom approved these changes

2022-12-07 10:22 UTC, soulBit approved these changes

2022-12-09 14:46 UTC, merged