SOV-132: feat(overlay): new overlay colors and tests
DistributedCollective/sovryn-dapp pull request #12
Opened 2022-09-23 07:56 UTC by creed-victor

[SOV-132](https://sovryn.atlassian.net/browse/SOV-132)

2022-09-27 07:02 UTC, tiltom requested changes

2022-09-27 07:02 UTC, tiltom commented on packages/ui/src/2_molecules/Overlay/Overlay.types.ts
> +  [OverlayBackground.default]: 'bg-gray-70 bg-opacity-[0.69]',
```suggestion
  [OverlayBackground.default]: 'bg-gray-70-ol',
```
I was looking at the design and you should use `rgba(44, 48, 59, 0.65)` for the default background. We already have that defined, it's `gray-70-ol` so you don't need to do it manually.

2022-09-27 07:02 UTC, tiltom commented on packages/ui/src/2_molecules/Overlay/Overlay.test.tsx
> +    }
```suggestion
callback?.();
```

2022-09-27 08:08 UTC, tiltom approved these changes

2022-09-27 23:05 UTC, soulBit approved these changes

2022-09-30 10:11 UTC, LunaSov approved these changes

2022-09-30 10:12 UTC, merged