SOV-991: zero sdk
DistributedCollective/sovryn-dapp pull request #123
Opened 2022-12-12 13:39 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-991

2022-12-13 09:51 UTC, Rickk137 requested changes

2022-12-13 09:51 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +                renderer={value => <>{formatValue(value, 3)} RBTC</>}
don't want to use newCollateralRenderer?

2022-12-13 09:51 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +            renderer={value => <>{formatValue(value, 3)}%</>}
usecallbak

2022-12-13 09:51 UTC, Rickk137 commented on apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
> +              <div>Collateral</div>
use translation

2022-12-13 09:51 UTC, Rickk137 commented on apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
> +              <div>Debt</div>
use translation

2022-12-13 10:48 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +                renderer={value => <>{formatValue(value, 3)} RBTC</>}
Hm, something is wrong, looks like my changes was reverted somewhere

2022-12-13 10:51 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +            renderer={value => <>{formatValue(value, 3)}%</>}
This one has no dependencies so it will not be updated unless value changes. `useCallback` in this case just decreases performance

2022-12-13 10:51 UTC, creed-victor commented on apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
> +              <div>Collateral</div>
That's just for testing purposes

2022-12-13 17:55 UTC, soulBit approved these changes
Made two changes that weren't present (first was missed from review in SOV-1013):
- Collateral ratio healthbar should have max of 250%
- Liquidation prices are now calculated dynamically based on latest adjusted debt/collateral ratio

2022-12-14 07:57 UTC, Rickk137 approved these changes

2022-12-14 07:57 UTC, merged