Feat/sov 1018 zero loc transaction history frame
DistributedCollective/sovryn-dapp pull request #124
Opened 2022-12-12 15:34 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1018

2022-12-13 10:55 UTC, Rickk137 requested changes

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +        false,
|| false?

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +          `${getTroveType(item.troveOperation)}`,
cellRenderer: (item: TroveChange) => getTroveType(item.troveOperation)

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +          </>
extract this to a function

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +                tooltipClassName="uppercase"
extract this to a function OR component

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +
here you should fetch the query again with 500 as pageSize. you can check the transaction export example

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +          )}
usecallback

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +          hideFirstPageButton
according to the design it should not be hidden

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +          dataAttribute="transaction-history-pagination"
pass totalItems if (trove.length  < pageSize)

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/locales/dayjs.ts
> +// Initialize dayjs
i think you can remove this

2022-12-13 10:55 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +      liquidationReserveAmount: renderLiquidationReserve(tx),
renderLiquidationReserve does not return a string so it won't show up correctly

2022-12-13 10:57 UTC, Rickk137 commented
Based on the spec checking all conditions is the same as checking none. but it's different
<img width="235" alt="Screen Shot 2022-12-13 at 2 26 20 PM" src="https://user-images.githubusercontent.com/25097709/207299490-427a8eb7-0e42-4ede-b593-fff4e4ca0f89.png">

2022-12-13 11:01 UTC, soulBit commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +
please also extract the 500 value for this limit to a constant called `EXPORT_RECORD_LIMIT` in `apps\frontend\src\utils\constants.ts` and update any locations where this should be used (here, in tx export example, and anywhere else this value is present)

2022-12-13 12:03 UTC, creed-victor requested changes

2022-12-13 12:03 UTC, creed-victor commented on apps/frontend/src/utils/helpers.ts
> +export function dateFormat(timestamp: number) {
```suggestion
export const dateFormat = (timestamp: number) => {
```
to make everything consistent

2022-12-13 12:10 UTC, pietro-maximoff commented
> Based on the spec checking all conditions is the same as checking none. but it's different <img alt="Screen Shot 2022-12-13 at 2 26 20 PM" width="235" src="https://user-images.githubusercontent.com/25097709/207299490-427a8eb7-0e42-4ede-b593-fff4e4ca0f89.png">

yep, i checked directly here  [https://zero-subgraph.test.sovryn.app/subgraphs/name/DistributedCollective/zero-subgraph/graphql](url) and if both these filters are selected - the graph returns an empty array, so I believe its a graphQL issue @BetsyBraddock is it possible to fix?

2022-12-13 17:15 UTC, creed-victor approved these changes

2022-12-13 17:54 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +        false,
rewritten in more detail

2022-12-13 17:54 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +          dataAttribute="transaction-history-pagination"
fixed with isNextButtonDisabled

2022-12-14 09:49 UTC, Rickk137 approved these changes

2022-12-16 09:53 UTC, merged