feat: add LOCStatus component
DistributedCollective/sovryn-dapp pull request #129
Opened 2022-12-16 09:57 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-1116

2022-12-16 10:32 UTC, creed-victor requested changes

2022-12-16 10:32 UTC, creed-victor commented on apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
> +              value={<CountUp separator="," suffix=" ZUSD" end={debt} />}
I think debt can be not only ZUSD, so it's better to pass symbol as prop

2022-12-16 12:13 UTC, creed-victor approved these changes

2022-12-19 12:55 UTC, soulBit approved these changes

2022-12-22 11:21 UTC, LunaSov approved these changes

2022-12-22 11:33 UTC, merged