add close LOC popup
DistributedCollective/sovryn-dapp pull request #132
Opened 2022-12-19 09:34 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1019

2022-12-19 12:44 UTC, creed-victor requested changes

2022-12-19 12:44 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
> +  }));
Move it outside of component

2022-12-19 12:44 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
> +  }, [creditValue, availableBalance]);
having useMemo would be cleaner:

```suggestion
  const hasError = useMemo(() => Number(availableBalance) < Number(creditValue), [creditValue, availableBalance]);
```

2022-12-19 14:19 UTC, creed-victor approved these changes

2022-12-20 14:00 UTC, tiltom requested changes

2022-12-20 14:00 UTC, tiltom commented on apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.tsx
> +      const logo = await getAssetLogo(asset);
Use `getTokenDetails` getter instead. I know you only need the logo but you can get rid of the logo resolving + the logo will be cached if you use the getter.

Also, fetch an asset logo only if it's needed (`showAssetLogo && !logo`).

2022-12-20 14:00 UTC, tiltom commented on apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.tsx
> +   * Applied data-layout-id to the outer element.
```suggestion
   * Applied data attribute to the outer element.
```

2022-12-20 14:00 UTC, tiltom commented on apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.module.css
> +.container {
There is `1rem` margin between `AssetRenderer` and the select button in the design but only `0.5rem` in the implementation. I think you need to add `0.5rem` to either `.container` or `.asset`.

Design:
<img width="146" alt="image" src="https://user-images.githubusercontent.com/14878713/208679831-ddfa30f2-3759-43d6-80d5-bd6615451b04.png">

Implementation:
<img width="1806" alt="image" src="https://user-images.githubusercontent.com/14878713/208680180-510ca5e3-7e29-49da-9139-b5bc5ca40c3b.png">

2022-12-20 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
> +      />
```suggestion
           <Paragraph
        className="font-medium"
        size={ParagraphSize.base}
        children={t(translations.closeCreditLine.title)}
        dataLayoutId="close-credit-line"
        style={ParagraphStyle.tall}
      />
```
Line height should be `1.25rem` according to the design.

2022-12-20 14:00 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
> +export const availableTokens = (tokens: SupportedTokens[]) =>
```suggestion
export const tokensToOptions = (tokens: SupportedTokens[]) =>
```

2022-12-20 14:00 UTC, tiltom commented on apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
> +      getZUSDBalance().then(balance => setZusdBalance(balance));
```suggestion
      getZUSDBalance().then(setZusdBalance);
```

2022-12-21 13:03 UTC, tiltom approved these changes

2022-12-23 12:17 UTC, LunaSov approved these changes

2022-12-23 12:28 UTC, LunaSov approved these changes

2022-12-23 16:07 UTC, merged