Feat/sov 1115 zero dashboard loc chart
DistributedCollective/sovryn-dapp pull request #135
Opened 2022-12-22 13:15 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1115

2022-12-22 14:26 UTC, creed-victor requested changes

2022-12-22 14:26 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/Chart/Chart.tsx
> +            },
```suggestion
            callback: (value) => Number(value + 1).toFixed(0),
```

2022-12-22 14:26 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/Chart/Chart.tsx
> +            },
```suggestion
            callback: (value) => `${Number(value).toFixed(0)} %`,
```

2022-12-22 15:47 UTC, creed-victor approved these changes

2022-12-23 10:31 UTC, Rickk137 requested changes

2022-12-23 10:31 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/Chart/Chart.tsx
> +export const Chart: FC = () => {
this is not a generic Chart. please rename it to a more related name like LOCChart

2023-01-11 11:50 UTC, soulBit approved these changes

2023-01-11 12:13 UTC, Rickk137 approved these changes

2023-01-11 13:54 UTC, merged