Sov 1096 notification stack
DistributedCollective/sovryn-dapp pull request #143
Opened 2023-01-09 15:57 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-1096

2023-01-10 17:23 UTC, soulBit requested changes

2023-01-10 17:23 UTC, soulBit commented on apps/frontend/src/contexts/NotificationContext.tsx
> +interface Props {
```suggestion
interface NotificationProviderProps {
```

2023-01-10 17:23 UTC, soulBit commented on apps/frontend/src/contexts/NotificationContext.tsx
> +export const NotificationProvider: React.FC<Props> = ({ children }) => {
```suggestion
export const NotificationProvider: React.FC<NotificationProviderProps> = ({ children }) => {
```

2023-01-10 17:23 UTC, soulBit commented on apps/frontend/src/contexts/NotificationContext.tsx
> +  const [time, setTime] = useState(new Date().getTime());
```suggestion
  const [time, setTime] = useState(Date.now());
```

2023-01-10 17:23 UTC, soulBit commented on apps/frontend/src/contexts/NotificationContext.tsx
> +      setTime(new Date().getTime());
```suggestion
      setTime(Date.now());
```

2023-01-10 17:23 UTC, soulBit commented on apps/frontend/src/contexts/NotificationContext.tsx
> +    (notification: NotificationItem, timeout = 5000) => {
Move the 5 second default timeout to a constant with name `DEFAULT_TIMEOUT_SECONDS`

2023-01-10 17:23 UTC, soulBit commented on packages/ui/src/2_molecules/NotificationStack/NotificationStack.stories.tsx
> +    console.log('onClose', id, items);
```suggestion
```

2023-01-10 17:23 UTC, soulBit commented on packages/ui/src/2_molecules/NotificationStack/NotificationStack.stories.tsx
> +  // now >fireTime + timeout;
```suggestion
```

2023-01-11 09:16 UTC, creed-victor approved these changes

2023-01-11 11:59 UTC, soulBit approved these changes

2023-01-11 13:17 UTC, LunaSov approved these changes

2023-01-11 13:31 UTC, merged