Sov 1287 zero stability pool page implementation
DistributedCollective/sovryn-dapp pull request #158
Opened 2023-01-17 11:06 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-1287

2023-01-18 08:54 UTC, pietro-maximoff requested changes

2023-01-18 08:54 UTC, pietro-maximoff commented on .env
> +REACT_APP_NETWORK=testnet
pls add a new line

2023-01-18 08:54 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
> +        gasLimit: gasLimit.mul(15).div(10).toString(),
since this calculation is used multiple times, you can store the result in a variable and reuse it instead of recalculating it each time.

2023-01-18 08:54 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
> +          gasLimit: gasLimit.mul(15).div(10).toString(),
since this calculation is used multiple times, you can store the result in a variable and reuse it instead of recalculating it each time.

2023-01-18 08:54 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
> +    if (!BigNumber.from(toWei(poolBalance)).isZero()) {
i believe it's better to move this computation to its own useMemo and pass it as a dependency there

2023-01-18 08:54 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
> +      return 'N/A';
use t(translations.common.na) and replace everywhere

2023-01-18 10:47 UTC, soulBit requested changes

2023-01-18 10:47 UTC, soulBit commented on .env
> +REACT_APP_GRAPH_ZERO=https://zero-subgraph.test.sovryn.app/subgraphs/name/DistributedCollective/zero-subgraph
Remove this file, I don't think this should be here

2023-01-18 10:47 UTC, soulBit commented on apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
> +        //Increase gas limit by 20% to make sure tx won't fail for this reason
```suggestion
        //TODO: replace with default gas limit - increase gas limit by 20% to make sure tx won't fail
```

Update comment here so we can find it easily later when we replace these with suggested default gas limits, and extract calculation to separate section (same thing for other instance)

2023-01-18 10:47 UTC, soulBit commented on apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
> +        <Button text="Done" onClick={onClose} className="w-full mt-7"></Button>
Add localisation for the button text

2023-01-18 10:47 UTC, soulBit commented on apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
> +            {...applyDataAttr('max-button')}
```suggestion
            {...applyDataAttr('earn-max-button')}
```

Prefix all the data attributes on this page with `earn-`

2023-01-18 10:47 UTC, soulBit commented on apps/frontend/src/app/5_pages/EarnPage/hooks/useHandleStabalityDeposit.ts
> +export const useHandleStabalityDeposit = (
```suggestion
export const useHandleStabilityDeposit = (
```
Rename file too

2023-01-18 10:47 UTC, soulBit commented on apps/frontend/src/router.tsx
> +        loader: zeroPageLoader,
If we are going to use the ethers-provider from this import, please extract the file from `apps\frontend\src\app\5_pages\ZeroPage\loader.ts` to somewhere else more generic - please discuss with team first, I suggest somewhere like `apps\frontend\src\store\EthersProviderLoader.ts` or similar (`store` folder maybe probably isn't quite correct)

2023-01-19 08:24 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
> +        gasLimit: gasLimit.mul(15).div(10).toString(),
well this is a temporary solution for now. cause we are planing to change gas limits in a separated story

2023-01-19 08:27 UTC, Rickk137 commented on apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
> +    if (!BigNumber.from(toWei(poolBalance)).isZero()) {
well this calculation is only used in here. so even if we move it to a separate useMemo that would be only used here so we are only adding a memory use and gain no performance improvements.

2023-01-19 17:34 UTC, soulBit requested changes
Few adjustments to make:
1. hide Deposit button if no existing SP deposit (since they are always depositing)
2. Title is not matching latest Figma: "Earn" -> "Stability Pool"
3. Reset the amount input value when switching between Deposit and Withdraw

2023-01-20 13:44 UTC, soulBit commented on apps/frontend/src/router.tsx
> +        loader: zeroPageLoader,
discussed with @Rickk137 and will be refactored separately

2023-01-20 13:45 UTC, soulBit commented on apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
> +        gasLimit: gasLimit.mul(15).div(10).toString(),
fine to leave here for now, we'll update it next sprint

2023-01-20 13:45 UTC, soulBit commented on apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
> +          gasLimit: gasLimit.mul(15).div(10).toString(),
fine to leave here for now, we'll update it next sprint

2023-01-20 14:46 UTC, soulBit requested changes
![image](https://user-images.githubusercontent.com/765825/213726179-c85aa2e3-7aca-4659-8a6f-3361a3a77ace.png)
In case of withdrawals, max amount should be SP balance (in this case it would be 25 ZUSD) - see point 3 in spec

2023-01-20 15:04 UTC, soulBit approved these changes

2023-01-20 15:12 UTC, pietro-maximoff approved these changes

2023-01-25 13:16 UTC, merged