SOV-1120: Redemptions history frame
DistributedCollective/sovryn-dapp pull request #168
Opened 2023-01-20 13:59 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1120

2023-01-23 10:06 UTC, Rickk137 requested changes

2023-01-23 10:06 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/hooks/useGetRedemptionsHistory.ts
> +});
we can move this to another file and import it from there

2023-01-23 10:06 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/hooks/useGetRedemptionsHistory.ts
> +  });
any reason we stopped using generated hooks?

2023-01-23 10:16 UTC, Rickk137 requested changes

2023-01-23 10:16 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
> +        cellRenderer: (item: Redemption) => renderZUSDRedeemed(item),
cellRenderer: renderZUSDRedeemed

2023-01-23 10:16 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
> +        cellRenderer: (item: Redemption) => renderRBTCReceived(item),
cellRenderer:renderRBTCReceived

2023-01-23 10:24 UTC, Rickk137 requested changes

2023-01-23 10:24 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
> +          rowTitle={row => generateRowTitle(row)}
rowTitle={generateRowTitle}

2023-01-23 11:03 UTC, Rickk137 requested changes

2023-01-23 11:03 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
> +          dataAttribute="transaction-history-table"
please update the dataAttribute and use applyDataAttr function

2023-01-23 11:03 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
> +          dataAttribute="transaction-history-pagination"
please update the dataAttribute and use applyDataAttr function

2023-01-24 08:50 UTC, Rickk137 approved these changes

2023-01-24 09:24 UTC, creed-victor approved these changes

2023-01-25 10:56 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
> +  }, [t, redemptions, addNotification]);
This is not quite right. If you think about it you are setting the setPageSize to 500 and then creating the CSV. The data takes time to be fetched so you end up getting the current pageSize (20) items exported. This needs to be change like the way i did for Collateral surplus withdrawals.
https://github.com/DistributedCollective/sovryn-dapp/pull/170/files#diff-5bf47db7ed7ad9aabfbaaca83181257902b6aa24880641c26d528a7edb578925R122-R152

2023-01-25 10:57 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
> +  }, [t, redemptions, addNotification]);
the same thing apply for TransactionHistoryFrame

2023-01-25 15:33 UTC, merged