SOV-1334: collateral surplus withdrawal history table
DistributedCollective/sovryn-dapp pull request #170
Opened 2023-01-23 11:11 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-1334

2023-01-24 09:21 UTC, creed-victor approved these changes

2023-01-24 11:03 UTC, pietro-maximoff requested changes

2023-01-24 11:03 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
> +            dataAttribute="history-address-id"
pls replace all dataAttribute with applyDataAtt

2023-01-24 11:03 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/hooks/useGetCollateralSurplusWithdrawals.ts
> +  const { loading, data } = useQuery(GetCollSurplusChangesDocument, {
you can use auto-generated hook as you mentioned before in my pr)

2023-01-25 11:31 UTC, pietro-maximoff approved these changes

2023-01-25 15:44 UTC, merged