SOV-1417: add Notification to Email Alert dialog
DistributedCollective/sovryn-dapp pull request #176
Opened 2023-01-25 18:48 UTC by soulBit

https://sovryn.atlassian.net/browse/SOV-1417

2023-01-26 09:24 UTC, tiltom requested changes

2023-01-26 09:24 UTC, tiltom commented on apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
> +          content: '',
```suggestion

```
`content` is an optional prop

2023-01-26 09:24 UTC, tiltom commented on apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
> +                content: '',
```suggestion
```

2023-01-26 09:24 UTC, tiltom commented on apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
> +              content: '',
```suggestion
```

2023-01-26 10:37 UTC, tiltom approved these changes

2023-01-31 10:45 UTC, LunaSov approved these changes

2023-01-31 14:24 UTC, merged