SOV-1118: Zero: SP transactions history frame
DistributedCollective/sovryn-dapp pull request #183
Opened 2023-01-27 15:09 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1118

2023-01-30 09:45 UTC, creed-victor approved these changes

2023-01-30 13:52 UTC, Rickk137 requested changes

2023-01-30 13:52 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
> +  );
Can you export this to a separated component to re-use in reward history

2023-01-30 16:29 UTC, Rickk137 approved these changes

2023-02-06 09:08 UTC, LunaSov approved these changes

2023-02-06 09:22 UTC, merged