SOV-1517: fix number inputs
DistributedCollective/sovryn-dapp pull request #187
Opened 2023-01-30 12:17 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-1517

2023-02-01 13:27 UTC, pietro-maximoff requested changes

2023-02-01 13:27 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +        value: `${formatValue(minCollateralAmount, 4)} RBTC`,
```suggestion
        value: `${formatValue(minCollateralAmount, 4)} ${SupportedTokens.rbtc}`,
```

2023-02-01 13:27 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +        value: `${formatValue(diff, 4)} RBTC`,
```suggestion
        value: `${formatValue(diff, 4)} ${SupportedTokens.rbtc}`,
```

2023-02-02 12:09 UTC, tiltom approved these changes

2023-02-04 10:50 UTC, tiltom approved these changes

2023-02-06 14:22 UTC, merged