[Heading] - add component
DistributedCollective/sovryn-dapp pull request #21
Opened 2022-10-01 09:35 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-510

2022-10-02 19:26 UTC, soulBit requested changes

2022-10-02 19:26 UTC, soulBit commented on packages/ui/src/1_atoms/Heading/Heading.module.css
> +  @apply font-roboto font-medium text-gray-10;
No changes required here now, but this can be removed once Paragraph is merged (since we then apply Roboto Medium globally)

2022-10-02 19:26 UTC, soulBit commented on packages/ui/src/1_atoms/Heading/Heading.test.tsx
> +describe('Heading', () => {
Add a test that checks whether a heading with a simple string of content renders as expected - e.g something like:

`expect(h1).toHaveTextContent('content check')`

2022-10-03 14:53 UTC, tiltom requested changes

2022-10-03 14:53 UTC, tiltom commented on packages/ui/src/1_atoms/Heading/Heading.module.css
> +  line-height: 18px;
```suggestion
  line-height: 1.125rem;
```

2022-10-03 14:53 UTC, tiltom commented on packages/ui/src/1_atoms/Heading/Heading.module.css
> +  line-height: 14px;
```suggestion
  line-height: 0.875rem;
```

2022-10-03 15:17 UTC, tiltom approved these changes

2022-10-04 06:50 UTC, creed-victor approved these changes

2022-10-06 11:10 UTC, LunaSov approved these changes

2022-10-06 12:00 UTC, soulBit approved these changes

2022-10-06 12:01 UTC, merged