SOV-1488: refactor error badge component
DistributedCollective/sovryn-dapp pull request #218
Opened 2023-02-12 13:39 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-1488

2023-02-13 10:46 UTC, soulBit requested changes

2023-02-13 10:46 UTC, soulBit commented on packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.test.tsx
> +  });
```suggestion
```

This only tests sub-set of functionality from 2nd test, consider adjusting to test level icons or another attribute not covered by other tests.

2023-02-13 10:46 UTC, soulBit commented on packages/ui/src/2_molecules/ErrorList/ErrorList.stories.tsx
> +    },
Add small test file for `ErrorList` component that checks whether errors are shown in expected order according to weight - e.g. for this case you see `weight 2, weight 1, weight 0`.

Can also add a test to check whether `showSingleError` prop works as intended

2023-02-15 12:00 UTC, soulBit approved these changes

2023-02-16 16:18 UTC, pietro-maximoff approved these changes

2023-02-16 16:19 UTC, merged