Sov 463 d 2 wc disconnect submenu implementation
DistributedCollective/sovryn-dapp pull request #22
Opened 2022-10-03 11:06 UTC by Rickk137

2022-10-04 07:05 UTC, creed-victor requested changes

2022-10-04 07:05 UTC, creed-victor commented on apps/frontend/tailwind.config.js
> +    '../../packages/ui/src/**/*.{html,ts,tsx,css}',
shouldn't be required and will not work once ui package is released to npm

2022-10-04 07:05 UTC, creed-victor commented on packages/tailwindcss-config/index.js
> +  content: ['./src/**/*.{html,ts,tsx,css}'],
should also work without `css`

2022-10-04 07:05 UTC, creed-victor commented on apps/frontend/src/app/2_molecules/WalletIdentity/WalletIdentity.tsx
> +import { DropdownSize } from '@sovryn/ui/src/2_molecules/Dropdown/Dropdown.types';
```suggestion
import { Dropdown, DropdownSize } from '@sovryn/ui';
```

2022-10-04 15:45 UTC, pietro-maximoff requested changes
reviewed, need some adjustments

2022-10-04 15:45 UTC, pietro-maximoff commented on apps/frontend/package.json
> +    "ethereum-blockies": "^0.1.1",
```suggestion
    "classnames": "2.3.2",
    "ethereum-blockies": "0.1.1",
```

2022-10-04 15:45 UTC, pietro-maximoff commented on apps/frontend/src/app/2_molecules/WalletIdentity/WalletIdentity.module.css
> +  @apply inline-flex items-center bg-gray-50 h-8 font-roboto text-gray-10 text-xs font-semibold px-2.5 leading-none select-none rounded;
```suggestion
  @apply inline-flex items-center bg-gray-50 h-8 font-roboto text-gray-10 text-xs font-semibold px-2 leading-none select-none rounded;
```
in design, I see 8px padding from the left and right sides

2022-10-04 15:45 UTC, pietro-maximoff commented on apps/frontend/src/app/2_molecules/WalletIdentity/components/AddressBadge/AddressBadge.tsx
> +          className="rounded-full mr-2"
```suggestion
          className="rounded-full mr-3"
```

2022-10-04 15:45 UTC, pietro-maximoff commented on apps/frontend/src/app/2_molecules/WalletIdentity/components/AddressBadge/AddressBadge.tsx
> +    <span className="flex flex-nowrap flex-row items-center w-full justify-between truncate font-semibold">
```suggestion
    <span className="flex flex-nowrap flex-row items-center w-full truncate font-semibold">
```

2022-10-04 15:45 UTC, pietro-maximoff commented on packages/ui/src/1_atoms/Icon/iconSvgPaths.ts
> +    'M12 3.11111L10.872 4.20778L12.936 6.22222H4.8V7.77778H12.936L10.872 9.78444L12 10.8889L16 7L12 3.11111ZM1.6 1.55556H8V0H1.6C0.72 0 0 0.7 0 1.55556V12.4444C0 13.3 0.72 14 1.6 14H8V12.4444H1.6V1.5
```suggestion
    'M18 4.88889L16.308 6.61222L19.404 9.77778H7.2V12.2222H19.404L16.308 15.3756L18 17.1111L24 11L18 4.88889ZM2.4 2.44444H12V0H2.4C1.08 0 0 1.1 0 2.44444V19.5556C0 20.9 1.08 22 2.4 22H12V19.5556H2.4V2.44444Z',
```
updated exit icon with 0 0 24 24 viewbox by default, 
and I'm not sure about changes in the icon component regarding iconProps, because in MenuItem we won't use icons with different sizes.
As I understand it, you are importing iconProps properties to change the viewBox and the size of the exit icon, 
we have a default size of 16px and the viewBox is 0 0 24 24, so if you just replace the exit icon with the default size, it will be the same as all others and the copy icon as well and you don't need to import iconProps

2022-10-04 15:45 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/Menu/components/MenuItem/MenuItem.tsx
> +  iconProps?: Omit<IconProps, 'icon'>;
see suggestion about an exit icon

2022-10-04 15:45 UTC, pietro-maximoff commented on apps/frontend/src/app/2_molecules/WalletIdentity/components/DisconnectSubmenu/DisconnectSubmenu.tsx
> +        iconProps={{ size: 16, viewBox: '0 0 16 14', className: 'mr-2' }}
we already have a 16px size of the icon by default, pls check my comment about the iconProps in iconSvgPaths.ts

2022-10-05 18:31 UTC, Rickk137 commented on apps/frontend/src/app/2_molecules/WalletIdentity/WalletIdentity.module.css
> +  @apply inline-flex items-center bg-gray-50 h-8 font-roboto text-gray-10 text-xs font-semibold px-2.5 leading-none select-none rounded;
the design is not correct, cause this component should have the same padding as dropdown does. Will ask gilad to update it

2022-10-05 18:33 UTC, Rickk137 commented on apps/frontend/src/app/2_molecules/WalletIdentity/components/AddressBadge/AddressBadge.tsx
> +          className="rounded-full mr-2"
<img width="194" alt="Screen Shot 2022-10-05 at 10 03 31 PM" src="https://user-images.githubusercontent.com/25097709/194135929-0ce7a79a-185b-406b-8211-a7076043b003.png">
Design shows 8px space

2022-10-05 18:43 UTC, pietro-maximoff commented on apps/frontend/src/app/2_molecules/WalletIdentity/WalletIdentity.module.css
> +  @apply inline-flex items-center bg-gray-50 h-8 font-roboto text-gray-10 text-xs font-semibold px-2.5 leading-none select-none rounded;
ah, got it

2022-10-05 18:46 UTC, pietro-maximoff commented on apps/frontend/src/app/2_molecules/WalletIdentity/components/AddressBadge/AddressBadge.tsx
> +          className="rounded-full mr-2"
yes, rechecked now and its 8px, yesterday it was 12px 🤔 don't know, maybe some kind of cache or something else, anyway thx for double checked that

2022-10-05 18:50 UTC, pietro-maximoff approved these changes

2022-10-06 06:46 UTC, creed-victor approved these changes

2022-10-08 09:44 UTC, creed-victor commented
@Rickk13, i think #27 has same changes but improvement ones. My suggestion is to close this PR and merge only wallet connection

2022-10-08 09:50 UTC, Rickk137 commented
> @rick23p, i think #27 has same changes but improvement ones. My suggestion is to close this PR and merge only wallet connection

Yes sure

2022-10-08 09:51 UTC, closed without merging