SOV-1796: Align amount field with the guideline
DistributedCollective/sovryn-dapp pull request #223
Opened 2023-02-15 12:20 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1796

2023-02-15 14:26 UTC, tiltom requested changes
1. `AmountRenderer` should be used in ”Current debt” on the homepage as well (also, by adding it to “Current collateral”, we broke the count-up functionality so fix it pls).
<img width="1175" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/14878713/219054841-f707ded7-b0d4-4b4e-a395-d47ca8f31e63.png">

2. There is a bug in `AmountRenderer` because I see “~” even though the number is not truncated.
<img width="172" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/14878713/219054962-522d46e0-4f3c-4b25-af99-bc3106a165b0.png">

2023-02-15 14:26 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/constants.ts
> +export const ASSET_TRUNCATE_COUNT = 4;
```suggestion
export const BTC_RENDER_PRECISION = 8;
export const TOKEN_RENDER_PRECISION = 4;
```

2023-02-15 14:26 UTC, tiltom commented on apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
> +        8,
```suggestion
        BTC_RENDER_PRECISION,
```

2023-02-15 14:26 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/AssetAmountCell/AssetAmountCell.tsx
>  type AssetAmountCellProps = {
You can delete this component and use `AmountRenderer` directly.

2023-02-15 14:26 UTC, tiltom commented on apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
> +                  4,
```suggestion
                  TOKEN_RENDER_PRECISION,
```

2023-02-15 14:26 UTC, tiltom commented on apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
> +                    4,
```suggestion
                    TOKEN_RENDER_PRECISION,
```

2023-02-15 14:26 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/CurrentTroveData.tsx
> +              suffix={DEBT_TOKEN.toUpperCase()}
```suggestion
              suffix={DEBT_TOKEN}
```

2023-02-16 16:08 UTC, pietro-maximoff commented
@tiltom I can't reproduce this - "There is a bug in AmountRenderer because I see “~” even though the number is not truncated." could you pls re-check it

2023-02-17 09:21 UTC, tiltom requested changes

2023-02-17 09:21 UTC, tiltom commented on apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
> +            separator=","
This is incorrect because you're hardcoding thousands separator - https://www.npmjs.com/package/react-countup#separator-string. You need to provide the correct value for given locale.

2023-02-17 09:21 UTC, tiltom commented on apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
> +          <CountUp
You also need to provide the correct decimals separator - https://www.npmjs.com/package/react-countup#decimal-string. That's why I currently see different separators for `Current collateral` and `Current debt` in `LOCStatus`, see the screenshot below.
<img width="1545" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/14878713/219603217-d140f508-71d0-4a99-85c1-6ea57a406ed7.png">

2023-02-17 09:21 UTC, tiltom commented on apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
>                  <AmountRenderer
You need to apply `isAnimated` prop here as well.

2023-02-17 09:23 UTC, tiltom commented
> @tiltom I can't reproduce this - "There is a bug in AmountRenderer because I see “~” even though the number is not truncated." could you pls re-check it

Yes, I can reproduce it - try to change your `collateral` value to `0.015` and you'll see it. I think it’s because of a weird determination if a tooltip should be disabled in `AmountRenderer`. We just need to split a string into integer and decimal parts and then compare if the decimal part is less or equal than the precision we want to achieve.

2023-02-17 09:24 UTC, tiltom commented
One new issue - `Current debt` is formatted differently in LOCStatus and Adjust LOC dialog.

<img width="1545" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/14878713/219605184-256dbd42-5ae5-47b3-834e-67a6ada71e38.png">

2023-02-20 13:05 UTC, tiltom requested changes

2023-02-20 13:05 UTC, tiltom commented on apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
> +  const countDecimalPlaces = useCallback((num, decimals) => {
This method is completely unnecessary:
1. Extract a method for determining the decimal part length - create a helper method in `math.ts`.
2. Use this method here and round the value with `toFixed` if `number of decimals > decimalPrecision`.

2023-02-20 13:05 UTC, tiltom commented on apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
> +            separator=","
@pietro-maximoff this has not been resolved (extract to a util function, e.g. `getThousandsSeparator`).

2023-02-20 13:05 UTC, tiltom commented on apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
> +            decimal="."
This is hardcoded as well, create a util function.

2023-02-20 13:06 UTC, tiltom commented
> > @tiltom I can't reproduce this - "There is a bug in AmountRenderer because I see “~” even though the number is not truncated." could you pls re-check it
> 
> Yes, I can reproduce it - try to change your `collateral` value to `0.015` and you'll see it. I think it’s because of a weird determination if a tooltip should be disabled in `AmountRenderer`. We just need to split a string into integer and decimal parts and then compare if the decimal part is less or equal than the precision we want to achieve.

@pietro-maximoff this is still happening, you haven't changed `tooltipDisabled` in `AmountRenderer`.

2023-02-21 16:30 UTC, tiltom approved these changes

2023-02-21 22:09 UTC, soulBit requested changes

2023-02-21 22:09 UTC, soulBit commented on apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
> +                  dataAttribute="LOC-debt"
```suggestion
                  dataAttribute="loc-status-debt"
```

2023-02-21 22:09 UTC, soulBit commented on apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
>                    dataAttribute="LOC-collateral"
```suggestion
                  dataAttribute="loc-status-collateral"
```

2023-02-22 11:17 UTC, soulBit approved these changes

2023-02-22 16:23 UTC, soulBit approved these changes

2023-03-01 10:21 UTC, merged