SOV-1458: updated LOC Chart
DistributedCollective/sovryn-dapp pull request #227
Opened 2023-02-16 13:09 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1458

2023-02-20 17:11 UTC, soulBit requested changes
Loading wallet with existing LoC looks totally broken:
![image](https://user-images.githubusercontent.com/765825/220167119-1ec47743-b529-4481-b6ab-cb8a0a5e229b.png)
I'll DM you the wallet address used here, others I tried looked ok.

2023-02-21 10:09 UTC, Rickk137 requested changes

2023-02-21 10:09 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetGlobalsEntity.ts
> +};
use auto generated hook with types

2023-02-23 17:31 UTC, soulBit approved these changes

2023-02-23 17:35 UTC, Rickk137 approved these changes

2023-02-23 20:21 UTC, merged