SOV-1578: single transaction DLLR
DistributedCollective/sovryn-dapp pull request #232
Opened 2023-02-20 12:36 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-1578

2023-02-21 14:57 UTC, tiltom requested changes

2023-02-21 14:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
> +          };
```suggestion
```
Use `UNSIGNED_PERMIT` instead.

2023-02-21 14:57 UTC, tiltom commented on apps/frontend/src/hooks/useAssetBalance.ts
> +          parsedValue: fromWei(e.result.value, tokenDetails.decimalPrecision),
I am getting these errors in the console, they are probably caused by this.
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/14878713/220376704-298c4f08-b91c-42be-ae43-da30abdba37c.png">

2023-02-21 14:57 UTC, tiltom commented on apps/frontend/src/hooks/useAssetBalance.ts
> +    parsedValue: '0',
It's a bit weird naming because `value` is basically `weiBalance` and `parsedValue` is `balance`. I'd propose to rename them so it's more clear.

2023-02-21 14:58 UTC, tiltom commented
@creed-victor - I also think you should reset AmountInput in the Stability pool form (both deposits and withdrawals) after a successful tx because you can end up with a weird state, such as the one on the screenshot.
<img width="539" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/14878713/220380043-ee1108f3-e0ea-4e85-8f86-4ca87f4b66ce.png">

2023-02-22 10:34 UTC, tiltom requested changes

2023-02-22 10:34 UTC, tiltom commented on apps/frontend/src/app/2_molecules/DashboardWelcomeBanner/components/ConnectedUserBanner/ConnectedUserBanner.tsx
> +  const { weiBalance, loading } = useAssetBalance(SupportedTokens.rbtc);
I'd say we should use `balance` here instead.

2023-02-22 10:34 UTC, tiltom commented on apps/frontend/src/app/2_molecules/ExampleBalanceCall.tsx
> +          Balance: {fromWei(result.balance)} {token}
`balance` is already a number converted from wei.

2023-02-22 10:34 UTC, tiltom commented on apps/frontend/src/app/3_organisms/Header/Header.tsx
> +  const { weiBalance } = useAssetBalance(SupportedTokens.rbtc);
I'd use `balance` instead.

2023-02-22 14:00 UTC, tiltom approved these changes

2023-02-22 15:35 UTC, soulBit approved these changes

2023-02-23 20:08 UTC, merged