SOV-1486: Create AssetValue component
DistributedCollective/sovryn-dapp pull request #238
Opened 2023-02-23 11:44 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1486

2023-02-23 18:20 UTC, soulBit approved these changes

2023-02-24 12:12 UTC, creed-victor requested changes

2023-02-24 12:12 UTC, creed-victor commented on apps/frontend/src/utils/math.ts
> +
Just use `Number(fromWei(amount, unit));` directly in the AssetValue component.

`Number` only supports 16 decimal places (while tokens have 18) and then rounds up everything so I would prefer not having such helpers exported so devs would not use them by mistake in the transactions.

2023-02-28 09:07 UTC, creed-victor approved these changes

2023-02-28 09:08 UTC, merged