feat: add Tabs component
DistributedCollective/sovryn-dapp pull request #24
Opened 2022-10-05 18:28 UTC by Rickk137

2022-10-11 07:23 UTC, tiltom requested changes

2022-10-11 07:23 UTC, tiltom commented on packages/tailwindcss-config/index.js
> +      'gray-80-ol': 'rgba(30, 33, 40, 0.65)',
According to the design, you should use `gray-50` for borders, is this something that was consulted with Gilad and hasn't been reflected in the design yet?

2022-10-11 07:23 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.stories.tsx
> +export const Basic = Template.bind({});
Create also an interactive template where you can click between tabs.

2022-10-11 07:23 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.tsx
> +interface ITabItem {
According to the spec, there should be `activeClassName` prop as well.

2022-10-11 07:23 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.tsx
> +  withBorder?: boolean;
I don't see this in the spec or design. If it was consulted and agreed on, update both.

2022-10-11 07:23 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.tsx
> +  style?: TabStyle;
```suggestion
  type?: TabType;
```
According to the spec, this should be called `type`.

2022-10-11 07:23 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.tsx
> +    <div className={classNames(className, 'inline-flex flex-col')}>
```suggestion
    <div className={classNames('inline-flex flex-col', className)}>
```

2022-10-11 07:23 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.tsx
> +      >
```suggestion
      <div
        className={classNames({
          'border-b border-x border-gray-50':
            withBorder && style === TabStyle.primary,
          'bg-gray-80 rounded-b': style === TabStyle.primary,
        }, contentClassName)}
      >
```

2022-10-11 07:23 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.types.ts
> +export enum TabColor {
I don't like the fact it contains `buy` and `sell` as it implies the usage (which is wrong in this case anyway). Btw, we discussed we would get rid of this enum, didn't we?

2022-10-11 07:23 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/components/Tab/Tab.module.css
> +  @apply font-roboto inline-flex box-border items-center justify-center text-center rounded cursor-pointer transition-colors;
```suggestion
  @apply inline-flex box-border items-center justify-center text-center rounded cursor-pointer transition-colors;
```
`font-roboto` is applied globally (`base.css`).

2022-10-11 07:23 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/components/Tab/Tab.module.css
> +    height: 47px;
We should always use `rem` for styling instead of `px` + `47px` and `155px` seem to me a bit more arbitrary.

2022-10-11 07:27 UTC, tiltom commented
Add some Jest tests as well.

2022-10-11 13:02 UTC, tiltom requested changes

2022-10-11 13:02 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.module.css
> +}
```suggestion
.wrapper {
  @apply inline-flex flex-col;
  
  .tabs {
    @apply inline-flex rounded-t items-center flex-nowrap overflow-auto;
    
    &.primary {
      @apply bg-gray-80/65;
      
      &.withBorder {
        @apply border border-b-0 border-gray-50;
      }
    }
  }
  .content {
    &.primary {
      @apply bg-gray-80 rounded-b;
      
      &.withBorder {
        @apply border-b border-x border-gray-50;
      }
    }
  }
}
```

2022-10-11 13:02 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.test.tsx
> +  });
```suggestion
  it('renders tabs', () => {
    const { getByText } = render(<Tabs items={items} index={1} />);

    expect(getByText('0')).toBeInTheDocument();
    expect(getByText('1')).toBeInTheDocument();
    expect(getByText('content-1')).toBeInTheDocument();
  });
```

2022-10-11 13:02 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.test.tsx
> +  it('switch between Tabs', () => {
```suggestion
  it('switch between tabs', () => {
```

2022-10-11 13:02 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.test.tsx
> +  it('switch to disabled Tab', () => {
```suggestion
  it('does not switch to a disabled tab', () => {
```

2022-10-11 13:02 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.tsx
> +  withBorder?: boolean;
I am still not sure about this property - from what I understand, it can only affect something if it's used with `TabType.primary`. I'd suggest adjusting the `TabType` enum so it would have the following values - `primary`, `secondary`, `primaryWithBorder` (or `primary`, `secondary`, `primaryWithoutBorder`).

What do you think @Rickk137 ? cc @soulBit

2022-10-11 13:02 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/Tabs.tsx
> +  );
```suggestion
  const selectTab = useCallback(
    (item: ITabItem, index: number) => {
      if (!item.disabled) {
        onChange?.(index);
      }
    },
    [onChange],
  );
```

2022-10-11 13:02 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/components/Tab/Tab.module.css
> +      &:last-child {
```suggestion
      @apply border-x border-x-gray-50;
      
      &:last-child {
```

2022-10-11 13:02 UTC, tiltom commented on packages/ui/src/1_atoms/Tabs/components/Tab/Tab.module.css
> +      &:not(:disabled):hover {
```suggestion
      @apply text-gray-10 opacity-75;
      
      &:not(:disabled):hover {
```

2022-10-11 16:44 UTC, soulBit requested changes

2022-10-11 16:44 UTC, soulBit commented on packages/ui/src/1_atoms/Tabs/Tabs.stories.tsx
> +      activeClassName: 'border-t-primary-30',
add example dataActionId prop to these item config objects, so QA have an example of how this is defined

2022-10-11 16:45 UTC, soulBit commented on packages/ui/src/1_atoms/Tabs/Tabs.tsx
> +  withBorder?: boolean;
@tiltom elegant suggestion, nice one :)

@Rickk137 please update as mentioned

2022-10-12 11:02 UTC, tiltom requested changes
The code itself looks fine but I noticed a difference between the design and implementation - there should be right/left borders between primary tabs.

Design:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/14878713/195326212-04ecc90a-3713-4873-92ca-73b52e236040.png">

Implementation:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/14878713/195326285-cff94307-a50d-4e01-a983-e7a5692f8ee0.png">

2022-10-12 11:03 UTC, soulBit approved these changes

2022-10-13 08:32 UTC, creed-victor approved these changes

2022-10-13 08:32 UTC, creed-victor commented on packages/ui/src/1_atoms/Tabs/components/Tab/Tab.module.css
> +    height: 47px;
change these to use `rem`s instead

2022-10-13 08:32 UTC, creed-victor commented on packages/ui/src/1_atoms/Tabs/components/Tab/Tab.module.css
> +      min-width: 54px;
use `rem`

2022-10-13 08:32 UTC, creed-victor commented on packages/ui/src/1_atoms/Tabs/components/Tab/Tab.module.css
> +      min-width: 41px;
also `rem`

2022-10-13 13:45 UTC, tiltom approved these changes

2022-10-14 11:32 UTC, LunaSov approved these changes

2022-10-14 13:29 UTC, merged