chore: repo config
DistributedCollective/sovryn-dapp pull request #25
Opened 2022-10-06 10:58 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-675

- ui package is bundled
- husky prettifies all staged files before commit
- eslint and jest checks are executed on staged files before commit
- changed components to use css module classes instead of tailwind directly

2022-10-11 10:52 UTC, soulBit approved these changes

2022-10-12 07:27 UTC, tiltom requested changes

2022-10-12 07:27 UTC, tiltom commented on packages/ui/src/2_molecules/Overlay/Overlay.module.css
> +  }
```suggestion
  &.fixed {
    @apply fixed;
  }

  &.absolute {
    @apply absolute;
  }
```
No need to follow `BEM` here.

2022-10-12 07:30 UTC, creed-victor commented on packages/ui/src/2_molecules/Overlay/Overlay.module.css
> +  }
`fixed` and `absolute` are existing default classes on tailwind - will cause error, happy to change to some different name

2022-10-12 07:37 UTC, tiltom commented on packages/ui/src/2_molecules/Overlay/Overlay.module.css
> +  }
Ah okay, I see that now. In that case it's fine and you can leave it as is :)

2022-10-12 07:38 UTC, tiltom approved these changes

2022-10-12 07:40 UTC, merged