feat: add forwardRef to interactive components SOV-698
DistributedCollective/sovryn-dapp pull request #26
Opened 2022-10-07 12:30 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-698

2022-10-08 15:47 UTC, soulBit approved these changes

2022-10-10 14:05 UTC, tiltom requested changes

2022-10-10 14:05 UTC, tiltom commented on packages/ui/src/2_molecules/Dropdown/Dropdown.test.tsx
> +    const { getByText } = render(<Dropdown ref={ref} text="Dropdown" children={data} />);
```suggestion
    render(<Dropdown ref={ref} text="Dropdown" children={data} />);
```

2022-10-11 07:24 UTC, tiltom approved these changes

2022-10-11 07:42 UTC, merged