SOV-1648: User's LOC is not highlighted in the chart
DistributedCollective/sovryn-dapp pull request #265
Opened 2023-03-02 16:23 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1648

2023-03-02 21:14 UTC, soulBit requested changes

2023-03-02 21:14 UTC, soulBit commented on apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
> +      const updatedTroves = troves.troves.map(trove => {
```suggestion
      const updatedTroves = troves.troves?.map(trove => {
```

2023-03-02 21:14 UTC, soulBit commented on apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetUserOpenTrove.ts
> +  const { data, loading } = useGetUserOpenTroveQuery({
When testing I can see this issue that is currently working fine on `develop`:
https://sovryn.atlassian.net/browse/SOV-1880

Chart should refresh whenever trove state changes

2023-03-02 21:14 UTC, soulBit commented on apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
> +        } as TroveData;
```suggestion
        return {
          id: trove.id,
          collateral: collateralAmount,
          debt: debtAmount,
          collateralRatioSortKey_legacy: trove.collateralRatioSortKey_legacy ?? '',
          collateralRatio: calculateCollateralRatio(
            collateralAmount,
            debtAmount,
            price,
          ),
        };
```

Potentially null/undefined value for `collateralRatioSortKey_legacy` is what causes the typecheck error, this code resolves it - unless you were worried about empty values?

2023-03-03 10:54 UTC, soulBit approved these changes

2023-03-03 11:37 UTC, Rickk137 approved these changes

2023-03-03 11:37 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
> +              return id.toLowerCase() === account.toLowerCase()
this comparison is being used a lot in the dapp. please add a function in utils and use it here:
```
export const areAddressesEqual = (address1: string, address2: string) =>
  address1.toLowerCase() === address2.toLowerCase();
```

2023-03-03 13:21 UTC, merged