Sov 464 d 2 wc connect wallet button
DistributedCollective/sovryn-dapp pull request #27
Opened 2022-10-07 18:18 UTC by Rickk137

2022-10-08 09:29 UTC, creed-victor requested changes
file is empty, can be deleted
`apps/frontend/src/app/2_molecules/ConnectWalletButton/ConnectWalletButton.module.css`

2022-10-08 09:29 UTC, creed-victor commented on apps/frontend/package.json
> +    "@sovryn/onboard-react": "^0.0.2",
```suggestion
    "@sovryn/onboard-common": "0.0.1",
    "@sovryn/onboard-core": "0.0.1",
    "@sovryn/onboard-injected": "0.0.1",
    "@sovryn/onboard-react": "0.0.2",
```

2022-10-08 09:29 UTC, creed-victor commented on apps/frontend/package.json
> +    "stream-browserify": "^3.0.0",
```suggestion
    "stream-browserify": "3.0.0",
```

2022-10-08 09:29 UTC, creed-victor commented on apps/frontend/src/app/2_molecules/WalletIdentity/WalletIdentity.module.css
> +.address-badge {
```suggestion
.addressBadge {
```

2022-10-08 09:29 UTC, creed-victor commented on apps/frontend/src/app/2_molecules/WalletIdentity/WalletIdentity.tsx
> +export const WalletIdentity: FC<PropsWithChildren<WalletIdentityProps>> = ({
I see no `children` used in component
```suggestion
export const WalletIdentity: FC<WalletIdentityProps> = ({
```

2022-10-08 09:29 UTC, creed-victor commented on apps/frontend/src/app/2_molecules/WalletIdentity/components/DisconnectSubmenu/DisconnectSubmenu.tsx
> +> = ({ address, onDisconnect, className }) => {
```suggestion
export const DisconnectSubmenu: FC<DisconnectSubmenuProps> = ({ address, onDisconnect, className }) => {
```

2022-10-08 09:29 UTC, creed-victor commented on apps/frontend/src/hooks/useWalletConnect.ts
> +  }, [wallets]);
disconnect all wallets
```suggestion
  const disconnectWallet = useCallback(async () => {
    await onboard.disconnectWallet();
  }, [wallets]);
```

2022-10-08 09:29 UTC, creed-victor commented on apps/frontend/src/hooks/useWalletConnect.ts
> +  }, []);
Allow user to select wallet type from list (btw looks like `injected` doesn't really work, correct would be `Metamask`, `Brave` and etc.)
```suggestion
  const connectWallet = useCallback(() => {
    onboard.connectWallet();
  }, [])
```

2022-10-08 10:15 UTC, creed-victor requested changes

2022-10-08 10:15 UTC, creed-victor commented on apps/frontend/src/hooks/useWalletConnect.ts
> +    const sub = onboard.state.select('wallets').subscribe(setWallets);
Feed subscription with already connected wallets when next opening page

```suggestion
    const sub = onboard.state.select('wallets').pipe(startWith(onboard.state.get().wallets)).subscribe(setWallets);
```

`import { startWith } from 'rxjs/operators';`

2022-10-08 10:15 UTC, creed-victor commented on apps/frontend/src/hooks/useWalletConnect.ts
> +  const [wallets, setWallets] = useState<WalletState[]>([]);
```suggestion
  const [wallets, setWallets] = useState<WalletState[]>(onboard.state.get().wallets);
```

2022-10-10 08:59 UTC, soulBit requested changes
Changes generally look good but I spotted two things that should be updated:
* startLength and endLength props are missing - please add

* WalletIdentity should have been done as UI library component since it can be reused outside of the WC flow - I’ve migrated it over and added Storybook examples for it, but can you please add Jest tests.

2022-10-10 12:22 UTC, creed-victor requested changes

2022-10-10 12:22 UTC, creed-victor commented on packages/ui/src/2_molecules/WalletIdentity/WalletIdentity.tsx
> +      className={classNames('w-40', className)}
add custom class to `styles` instead of using `w-40`

2022-10-10 12:22 UTC, creed-victor commented on packages/ui/src/2_molecules/WalletIdentity/components/AddressBadge/AddressBadge.tsx
> +    </span>
add custom classes to css modules instead of using tailwindcss directly in the component

2022-10-10 13:37 UTC, soulBit commented
@Rickk137 I added default prop values for startLength and endLength (default for startLength was previously 6 which did not match spec)

2022-10-10 20:22 UTC, soulBit approved these changes
Noticed two things whilst reviewing tests - there was hardcoded label text in the DisconnectSubmenu component, but all text should be passed in as props to allow for localizations on dapp side. Data-action-id wasn't being used etiher (but these weren't part of spec so no issues :)) I've updated these points and tests/stories to match.

2022-10-11 06:53 UTC, creed-victor approved these changes

2022-10-11 12:06 UTC, LunaSov approved these changes

2022-10-12 10:00 UTC, merged