chore: added email landing pages
DistributedCollective/sovryn-dapp pull request #276
Opened 2023-03-06 09:08 UTC by pietro-maximoff

this PR will add email landing pages from these tasks:
https://sovryn.atlassian.net/browse/SOV-1727
https://sovryn.atlassian.net/browse/SOV-1729
https://sovryn.atlassian.net/browse/SOV-1731
https://sovryn.atlassian.net/browse/SOV-1733
https://sovryn.atlassian.net/browse/SOV-1735

**Additional changes:**
 - added some cleanup in the dapp2 header
 - updated styles for the dapp2 footer to make it consistent with email landing pages

2023-03-06 10:20 UTC, tiltom requested changes

2023-03-06 10:20 UTC, tiltom commented on apps/frontend/src/app/3_organisms/Footer/Footer.tsx
> +      <div className="flex flex-col md:flex-row justify-center flex-wrap gap-x-7 gap-y-4 md:mt-0 mt-4">
Links are not centered in the footer, fix it pls.
<img width="518" alt="image" src="https://user-images.githubusercontent.com/14878713/223076344-8c10fbb6-dbf0-4fa5-9d05-f35ee1f5869e.png">

2023-03-06 10:20 UTC, tiltom commented on apps/frontend/src/app/5_pages/EmailVerifiedPage/EmailVerifiedPage.tsx
> +          {t(translations.emailNotifications.verifyPage.meta.title)}
The title should be "Verified - Sovryn" according to the spec. It's "Verify email - Sovryn" now, fix it.
<img width="144" alt="image" src="https://user-images.githubusercontent.com/14878713/223078350-14deb422-2573-43ee-a491-7e999321cb22.png">

2023-03-06 10:20 UTC, tiltom commented on apps/frontend/src/app/5_pages/EmailDuplicateVerifiedPage/EmailDuplicateVerifiedPage.tsx
> +export const EmailDuplicateVerifiedPage = () => {
I really don't like the fact you have 5 pages with the exact same markup. Create a component that accepts `metaTitle`, `title` and `subtitle` as props and use it in the pages instead.

2023-03-06 10:20 UTC, tiltom commented on apps/frontend/src/locales/en/translations.json
> +        "verifyPage": {
```suggestion
        "verifiedPage": {
```

2023-03-06 10:20 UTC, tiltom commented on apps/frontend/src/utils/constants.ts
> +  blog: 'https://sovryn.app/all-things-sovryn',
```suggestion
  blog: 'https://sovryn.com/all-things-sovryn',
```
I believe this should be `sovryn.com` and not `sovryn.app`, am I right @soulBit ?

2023-03-06 10:20 UTC, tiltom commented on apps/frontend/src/utils/constants.ts
> +export const sovrynAlfaStagingLink = 'https://alfa-staging.sovryn.app';
```suggestion
export const sovrynAlphaStagingLink = 'https://alpha-staging.sovryn.app';
```

2023-03-06 10:20 UTC, tiltom commented on apps/frontend/src/app/4_templates/PageEmailContainer/components/PageEmailContainerFooter/PageEmailContainerFooter.tsx
> +export const PageEmailContainerFooter: FC = () => (
I don't see a reason for having the exact same component in our solution twice, if the only difference is the first link. I think you should discuss it with @john-light to see if you can have the same link in both footer components we have and that would mean you can delete this one.

What do you think @soulBit ?

2023-03-06 10:31 UTC, pietro-maximoff commented on apps/frontend/src/utils/constants.ts
> +  blog: 'https://sovryn.app/all-things-sovryn',
on the 9th, we'll deploy D2 to sovryn.app

2023-03-06 10:35 UTC, tiltom commented on apps/frontend/src/utils/constants.ts
> +  blog: 'https://sovryn.app/all-things-sovryn',
I know but `.app` should be used only for apps and `.com` is where our blog is.

2023-03-06 10:42 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/Footer/Footer.tsx
> +      <div className="flex flex-col md:flex-row justify-center flex-wrap gap-x-7 gap-y-4 md:mt-0 mt-4">
@tiltom please add a link to the layout where they should be centered

2023-03-06 10:53 UTC, soulBit commented on apps/frontend/src/app/4_templates/PageEmailContainer/components/PageEmailContainerFooter/PageEmailContainerFooter.tsx
> +export const PageEmailContainerFooter: FC = () => (
agreed

2023-03-06 10:56 UTC, soulBit commented on apps/frontend/src/utils/constants.ts
> +  blog: 'https://sovryn.app/all-things-sovryn',
@pietro-maximoff D2 will live on `sovryn.app` and `test.sovryn.app`, tiltom is correct here

2023-03-06 10:57 UTC, soulBit commented on apps/frontend/src/app/3_organisms/Footer/Footer.tsx
> +      <div className="flex flex-col md:flex-row justify-center flex-wrap gap-x-7 gap-y-4 md:mt-0 mt-4">
layout looks correct, marking comment as resolved (@tiltom if you spotted somewhere this is incorrectly detailed then let me know)

2023-03-06 11:09 UTC, soulBit requested changes

2023-03-06 11:09 UTC, soulBit commented on apps/frontend/src/locales/en/translations.json
> +                "title": "Verify email - Sovryn"
```suggestion
                "title": "Verified - Sovryn"
```

Incorrect as per spec

2023-03-06 11:12 UTC, pietro-maximoff commented on apps/frontend/src/locales/en/translations.json
> +                "title": "Verify email - Sovryn"
it's already fixed, just need to push my updates

2023-03-06 11:30 UTC, pietro-maximoff commented on apps/frontend/src/app/4_templates/PageEmailContainer/components/PageEmailContainerFooter/PageEmailContainerFooter.tsx
> +export const PageEmailContainerFooter: FC = () => (
sure, i can do it

2023-03-06 12:12 UTC, tiltom commented on apps/frontend/src/app/3_organisms/Footer/Footer.tsx
> +      <div className="flex flex-col md:flex-row justify-center flex-wrap gap-x-7 gap-y-4 md:mt-0 mt-4">
I was talking about vertical centering, sorry for not being clear in the initial comment.

2023-03-06 16:47 UTC, tiltom requested changes

2023-03-06 16:47 UTC, tiltom commented on apps/frontend/src/app/2_molecules/EmailContentRenderer/EmailContentRenderer.tsx
> +export const EmailContentRenderer: React.FC<EmailContentRendererProps> = ({
The name of the component is really misleading - you don't render any email content with it. I think something like `EmailVerificationState` is more suitable.

2023-03-06 16:47 UTC, tiltom commented on apps/frontend/src/app/3_organisms/Footer/Footer.tsx
> +            id: 'Dashboard',
```suggestion
            id: 'dashboard',
```

2023-03-06 16:47 UTC, tiltom commented on apps/frontend/src/app/3_organisms/Footer/Footer.tsx
> +  isEmailPage?: boolean;
```suggestion
  isEmailVerificationStatePage?: boolean;
```

2023-03-06 16:47 UTC, tiltom commented on apps/frontend/src/app/4_templates/PageEmailContainer/PageEmailContainer.tsx
> +export const PageEmailContainer: FC<PageEmailContainerProps> = ({
```suggestion
export const EmailVerificationStateContainer: FC<PageEmailContainerProps> = ({
```

2023-03-06 16:47 UTC, tiltom commented on apps/frontend/src/app/5_pages/EmailDuplicateVerifiedPage/EmailDuplicateVerifiedPage.tsx
> +};
```suggestion
export const EmailDuplicateVerifiedPage = () => (
  <EmailContentRenderer
    metaTitle={t(
      translations.emailNotifications.duplicateVerifiedPage.meta.title,
    )}
    title={t(translations.emailNotifications.duplicateVerifiedPage.title)}
    subtitle={t(translations.emailNotifications.duplicateVerifiedPage.subtitle)}
  />
);
```
Unnecessary return, do the same change for all the email verification state pages.

2023-03-06 18:06 UTC, soulBit requested changes

2023-03-06 18:06 UTC, soulBit commented on apps/frontend/src/utils/constants.ts
> +export const sovrynAlphaStagingLink = 'https://alpha-staging.sovryn.app';
Ideally this would be in `sovrynAlphaLinks` instead, but since staging is a bit of special case and we don't have `Environments` env var it, I suggest just moving this to line 20 so that it's at least next to the rest of the Alpha dapp links.

2023-03-06 18:06 UTC, soulBit commented on apps/frontend/src/app/5_pages/EmailErrorPage/EmailErrorPage.tsx
> +const LINK_TEXT = 'help.sovryn.app';
This is the same thing as `helpdeskLink` but with just middle part of path, maybe better to strip those bits out and use that, instead of redefining (most of) the URL here?

2023-03-06 21:44 UTC, soulBit requested changes

2023-03-06 21:44 UTC, soulBit commented on apps/frontend/src/utils/constants.ts
>  export const sovrynWikiLinks = {
```suggestion
  [Environments.Testnet]: 'https://alpha-test.sovryn.app',
};
export const sovrynAlphaStagingLink = 'https://alpha-staging.sovryn.app';

export const sovrynStagingLink = 'https://staging.sovryn.app';

```

Sorry I wasn't clear, like this - just the alpha link :)

2023-03-07 09:27 UTC, tiltom approved these changes

2023-03-07 10:24 UTC, soulBit approved these changes

2023-03-07 10:25 UTC, merged