SOV-1763: Origination fee calculation/display in history table
DistributedCollective/sovryn-dapp pull request #286
Opened 2023-03-11 08:15 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1763

2023-03-12 09:32 UTC, tiltom requested changes

2023-03-12 09:32 UTC, tiltom commented on apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +        Math.trunc((Number(borrowingFee) / Number(debtChange)) * 1e4) / 100;
```suggestion
      const originationFeePercentage =
        Math.trunc((Number(borrowingFee) / Number(debtChange)) * 1e4) / 100;
```

2023-03-13 08:44 UTC, creed-victor approved these changes

2023-03-13 10:33 UTC, tiltom approved these changes

2023-03-13 10:34 UTC, merged