SOV-1943: new collateral ratio must be increased in recovery mode
DistributedCollective/sovryn-dapp pull request #291
Opened 2023-03-14 08:32 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-1943

2023-03-14 13:54 UTC, tiltom requested changes

2023-03-14 13:54 UTC, tiltom commented on apps/frontend/src/locales/en/translations.json
> +                "ratioDecreased": "New collateral must be greater than {{value}}%",
```suggestion
                "ratioDecreased": "New collateral ratio must be greater than {{value}}%",
```

2023-03-14 13:58 UTC, tiltom approved these changes

2023-03-14 20:03 UTC, soulBit approved these changes

2023-03-21 12:09 UTC, tiltom approved these changes

2023-03-22 10:52 UTC, merged