SOV-580: vertical tabs component
DistributedCollective/sovryn-dapp pull request #30
Opened 2022-10-14 12:59 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-580

2022-10-18 08:32 UTC, pietro-maximoff requested changes
need small fixes, in general, all great

2022-10-18 08:32 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.module.css
> +  background-color: inherit;
```suggestion
  @apply w-full h-full p-[3.25rem] relative overflow-y-auto bg-inherit;
```

2022-10-18 08:32 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.module.css
> +
```suggestion
```

2022-10-18 08:32 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.module.css
> +
```suggestion
```

2022-10-18 08:32 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.module.css
> +  border-style: solid;
```suggestion
  @apply absolute right-0 w-0 h-0 border-solid;
  transform: translate(0, -1.7rem);
```

2022-10-18 08:32 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.tsx
> +  dataActionId,
i think makes sense to change it now dataActionId -> dataLayoutId and ping Alita or Luna to update test cases

2022-10-18 11:06 UTC, Rickk137 requested changes

2022-10-18 11:06 UTC, Rickk137 commented on packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.module.css
> +  background-color: inherit;
bg-inherit

2022-10-18 11:06 UTC, Rickk137 commented on packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.module.css
> +  @apply w-full flex flex-col justify-center items-center gap-y-[2.5rem];
gap-y-10

2022-10-18 11:06 UTC, Rickk137 commented on packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.types.ts
> +  dataActionId?: string;
could you change it to dataLayoutId

2022-10-18 11:06 UTC, Rickk137 commented on packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.module.css
> +    @apply text-base leading-[1.171875rem];
``1.171875rem`` value is very custom. i think we should ask designer not to use it

2022-10-18 11:06 UTC, Rickk137 commented on packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.module.css
> +  @apply w-full block text-left text-gray-10 text-opacity-50 font-medium font-roboto;
font-roboto is applied in via global class

2022-10-18 11:06 UTC, Rickk137 commented on packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.tsx
> +      data-action-id={dataActionId}
data-layout-id

2022-10-18 11:37 UTC, creed-victor commented on packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.module.css
> +  background-color: inherit;
removed entirely, will not be used.

2022-10-18 11:37 UTC, creed-victor commented on packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.module.css
> +  border-style: solid;
removed entirely, will not be used.

2022-10-18 11:37 UTC, creed-victor commented on packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.module.css
> +  background-color: inherit;
removed entirely, will not be used.

2022-10-18 16:20 UTC, pietro-maximoff approved these changes

2022-10-18 16:21 UTC, Rickk137 commented
@creed-victor Looks good. Only if you could add a on hover style to the VerticalTabItem

2022-10-18 16:21 UTC, Rickk137 commented
@creed-victor also there is a conflict

2022-10-18 16:23 UTC, Rickk137 approved these changes

2022-10-19 13:06 UTC, LunaSov approved these changes

2022-10-19 13:06 UTC, merged