feat: SOV-2025 add loader screens
DistributedCollective/sovryn-dapp pull request #319
Opened 2023-03-24 13:40 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-2025

2023-03-24 18:27 UTC, soulBit requested changes

2023-03-24 18:27 UTC, soulBit commented on apps/frontend/src/app/0_meta/DeferedDataLoader/withDeferedRouterData.tsx
> +};
```suggestion
) => (props: C) => {
    const data = useLoaderData() as T;
    return (
      <React.Suspense fallback={<LoaderWithLogo />}>
        <Await
          resolve={key ? data[key] : data}
          errorElement={<ErrorRenderer />}
        >
          {(data: T) => <Component {...props} defered={data} />}
        </Await>
      </React.Suspense>
    );
  };
```

2023-03-24 18:27 UTC, soulBit commented on apps/frontend/src/app/1_atoms/LoaderWithLogo/LoaderWithLogo.tsx
> +      <svg
Not sure if you did it for performance reasons, but otherwise we could move this to an actual SVG file and import it instead (easier to preview file and track changes that way)

2023-03-24 18:27 UTC, soulBit commented on apps/frontend/src/styles/tailwindcss/components.css
> +      @apply font-montserrat normal-case no-underline text-sov-white text-base transition;
```suggestion
      @apply normal-case no-underline text-sov-white text-base transition;
```

Please test it, but I think we can just remove the font setting here and on line 30, or change to `font-body` (we should be using Roboto for everything, unless I missed this somewhere in designs)

2023-03-24 18:27 UTC, soulBit commented on apps/frontend/src/app/1_atoms/ErrorRenderer/ErrorRenderer.tsx
> +            <Lottie animation="spaceScene" />
Could you replace current animation with this one:
https://lottiefiles.com/69657-bug-hunting
and add the space one to `NotFoundPage` instead?

Once implemented we'll get it approved by Product, I really like them 😄

2023-03-24 18:27 UTC, soulBit commented on apps/frontend/src/app/1_atoms/ErrorRenderer/ErrorRenderer.tsx
> +        <p>{t(translations.errorPage.description)}</p>
Replace this with same UI components used on `NotFoundPage` (Heading/Paragraph)

2023-03-24 18:27 UTC, soulBit commented on apps/frontend/src/app/5_pages/ErrorPage/ErrorPage.tsx
> +            )}
Since we're editing this part now let's also update it to use Paragraph component

2023-03-24 18:27 UTC, soulBit commented on apps/frontend/src/app/0_meta/DeferedDataLoader/withDeferedRouterData.tsx
> +  C extends { defered: T },
```suggestion
export const withDeferredLoaderData = <
  T extends object,
  C extends { deferred: T },
```
Sorry to make you change this as its in multiple files, but "deferred" has two r's in it

2023-03-24 18:27 UTC, soulBit commented on apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
> +export default withDeferedLoaderData(ZeroPage, 'deferedData');
```suggestion
export default withDeferredLoaderData(ZeroPage, 'deferredData');
```

See comment in `withDeferedRouterData.tsx`

2023-03-24 18:27 UTC, soulBit commented on apps/frontend/public/index.html
> +        margin-top: 10px;
```suggestion
        margin-top: 18px;
```

increase text size slightly as well please

2023-03-25 09:50 UTC, creed-victor commented on apps/frontend/src/styles/tailwindcss/components.css
> +      @apply font-montserrat normal-case no-underline text-sov-white text-base transition;
It was set to montserrat for header so I think it's correct (font-body was montserrat). If it should not be a montserrat, then font should be removed from the project entirely as it's not used anywhere else

2023-03-25 19:03 UTC, soulBit commented on apps/frontend/src/styles/tailwindcss/components.css
> +      @apply font-montserrat normal-case no-underline text-sov-white text-base transition;
Ok let's leave it and we'll remove it in another story, thanks

2023-03-25 19:03 UTC, soulBit approved these changes

2023-03-27 07:42 UTC, tiltom requested changes

2023-03-27 07:42 UTC, tiltom commented on apps/frontend/src/app/1_atoms/LoaderWithLogo/LoaderWithLogo.tsx
> +};
```suggestion
export const LoaderWithLogo: FC<LoaderWithLogoProps> = ({ text }) => (
  <div className="flex flex-col justify-center items-center flex-grow">
    <LogoSVG className="sv-logo" />
    <div className="sv-loading-text">
      {text ? text : t(translations.loader.loading)}
    </div>
  </div>
);
```

2023-03-27 07:42 UTC, tiltom commented on apps/frontend/src/app/5_pages/ErrorPage/ErrorPage.tsx
> +            {process.env.NODE_ENV === 'development' && (
Extract the condition to a util method (e.g. `isTestnet`) and place it to `helpers.ts`.

2023-03-28 08:13 UTC, tiltom approved these changes

2023-03-28 08:13 UTC, tiltom commented on apps/frontend/src/app/5_pages/ErrorPage/ErrorPage.tsx
> +            {isDevEnvironment() && (
Pls update 2 other locations where we use the condition (`wdyr.ts` and `useDepositSocket`) as well.

2023-04-05 08:57 UTC, merged