SOV-1906: Constants refactoring
DistributedCollective/sovryn-dapp pull request #330
Opened 2023-04-03 14:03 UTC by tiltom

Resolves https://sovryn.atlassian.net/browse/SOV-1906

2023-04-03 23:44 UTC, soulBit requested changes

2023-04-03 23:44 UTC, soulBit commented on apps/frontend/src/constants/gasLimits.ts
> +  TRANSFER_LOC: 900000,
```suggestion
  MAX: 6_800_000,
  OPEN_TROVE: 1_100_000,
  ADJUST_TROVE: 4_000_000,
  CLOSE_TROVE: 350_000,
  CLOSE_DLLR_TROVE: 500_000,
  CONVERT: 200_000,
  STABILITY_POOL: 250_000,
  STABILITY_POOL_INC_WITHDRAW: 490_000,
  STABILITY_POOL_DLLR: 500_000,
  STABILITY_POOL_DLLR_INC_WITHDRAW: 690_000,
  REWARDS: 240_000,
  TRANSFER_LOC: 900_000,
```

2023-04-03 23:44 UTC, soulBit commented on apps/frontend/src/constants/infrastructure.ts
> +export const RSK_EXPLORER = {
```suggestion

//TODO: refactor this into separate dictionary file once we add more chains
export const RSK_EXPLORER = {
```

2023-04-03 23:44 UTC, soulBit commented on apps/frontend/src/constants/general.ts
> +export const BTC_IN_SATOSHIS = 100000000;
```suggestion
export const BTC_IN_SATOSHIS = 100_000_000;
```

2023-04-03 23:44 UTC, soulBit commented on apps/frontend/src/constants/currencies.ts
> +export const USD = 'USD';
Extract the `XX_RENDER_PRECISION` constants from `apps\frontend\src\app\3_organisms\ZeroLocForm\constants.ts` here as well, they are used in other places than just LoC form

2023-04-04 08:18 UTC, creed-victor approved these changes

2023-04-04 19:00 UTC, soulBit approved these changes

2023-04-04 19:00 UTC, merged