SOV-2145: add Adjust - Borrow LOC maintenance states
DistributedCollective/sovryn-dapp pull request #340
Opened 2023-04-12 14:44 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-2145

2023-04-12 15:13 UTC, creed-victor requested changes

2023-04-12 15:13 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
> +    () => borrowLocked && props.hasTrove && props.debtType === AmountType.Add,
```suggestion
    () => borrowLocked && (props.hasTrove && props.debtType === AmountType.Add || !props.hasTrove),
```

2023-04-12 15:13 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
> +  debtType: AmountType;
When opening trove, `hasTrove` is always `false` and always `true` for Adjusting.
So it means that you don't need to add `debtType` here, `hasTrove == false` is same as `debtType == AmountType.Add`

2023-04-12 15:13 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
> +      debtType={AmountType.Add}
```suggestion
```

2023-04-12 15:13 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
> +import { AmountType, CreditLineSubmitValue } from '../types';
```suggestion
import { CreditLineSubmitValue } from '../types';
```

2023-04-13 12:24 UTC, creed-victor approved these changes

2023-04-15 16:51 UTC, soulBit approved these changes

2023-04-15 16:51 UTC, soulBit commented on .changeset/six-seals-confess.md
> +SOV-2145: add Adjust - Borrow LOC
```suggestion
SOV-2145: add Adjust - Borrow LOC maintenance states
```

2023-04-19 14:42 UTC, merged