SOV-2117: Add stability pool subsidies details to the Earn and Rewards pages
DistributedCollective/sovryn-dapp pull request #362
Opened 2023-04-26 12:58 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-2117

2023-04-26 13:56 UTC, tiltom requested changes

2023-04-26 13:56 UTC, tiltom commented on apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
> +                <span className="relative">
`HelperButton` is not vertically centered, use divs and flexbox.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/14878713/234589726-5f2716c9-942e-4daf-b86a-42ccd9b70479.png">

2023-04-26 13:56 UTC, tiltom commented on apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
> +              value={`${formatValue(apy, 5)}% APY`}
I already mentioned it in the story but the value should be rounded to 2 decimals.

2023-04-26 13:56 UTC, tiltom commented on apps/frontend/src/app/5_pages/EarnPage/hooks/useGetSubsidiesAPR.ts
> +  const getCommunityIssuance = useCallback(async () => {
Use `useLoadContract` hook instead.

2023-04-26 13:56 UTC, tiltom commented on apps/frontend/src/app/5_pages/EarnPage/hooks/useGetSubsidiesAPR.ts
> +  }, [apr]);
```suggestion
  const apy = useMemo(
    () => (Math.pow(1 + apr / 36525, 365.25) - 1) * 100,
    [apr],
  );
```

2023-04-26 13:56 UTC, tiltom commented on apps/frontend/src/app/5_pages/EarnPage/hooks/useGetSubsidiesAPR.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Do you need it?

2023-04-26 13:56 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetSovGain.ts
> +    );
Use `useLoadContract` hook.

2023-04-26 13:56 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetSovGain.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Is it necessary?

2023-04-26 14:28 UTC, tiltom requested changes

2023-04-26 14:28 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetSovGain.ts
> +    setSOVGain(formatUnits(gain.toString()));
```suggestion
    setSOVGain(fromWei(gain.toString()));
```
Use `fromWei` from `utils/math.ts`. It's using `formatUnits` under the hood but I prefer to use our helpers.

2023-04-26 14:28 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetSovGain.ts
> +  );
```suggestion
  const stabilityPool = useLoadContract(
    'stabilityPool',
    'zero'
  );
```
No need to specify the chain id (unless you want to use something else than RSK).

2023-04-26 14:28 UTC, tiltom commented on apps/frontend/src/app/5_pages/EarnPage/hooks/useGetSubsidiesAPR.ts
> +  );
```suggestion
  const communityIssuance = useLoadContract(
    'communityIssuance',
    'zero'
  );
```

2023-04-26 14:57 UTC, tiltom approved these changes

2023-04-27 13:40 UTC, soulBit approved these changes

2023-04-27 13:40 UTC, merged