SOV-2083: add links to alpha
DistributedCollective/sovryn-dapp pull request #365
Opened 2023-04-27 11:49 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-2083

2023-04-27 13:13 UTC, tiltom requested changes
Except the code issues, there are 2 issues that need to be fixed:
1. The D1 links in the mobile menu have completely different typography than regular links. Also, there's some margin/padding on the left. Make them consistent with the D1 links pls.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/14878713/234872632-fa8445f0-e8b7-4484-965a-3b52d34a60ee.png">

2. Remove "Sovryn Alpha" link from the Footer (it's in the spec).

2023-04-27 13:13 UTC, tiltom commented on apps/frontend/src/app/3_organisms/Header/components/ProductLinks/ProductLinks.tsx
> +  : 'https://bitocracy.test.sovryn.app';
Extract these 2 links to `links.ts` (`BITOCRACY_LINKS`).

2023-04-27 13:13 UTC, tiltom commented on apps/frontend/src/app/3_organisms/Header/components/ProductLinks/ProductLinks.tsx
> +const linkToAlpha = (path?: string) =>
Extract this logic (without path concatenation) to `helpers.ts` (similar to `D2_URL` in D1).

2023-04-27 13:13 UTC, tiltom commented on apps/frontend/src/app/3_organisms/Header/components/ProductLinks/ProductLinks.tsx
> +const linkToBitocracy = isMainnet()
Extract this logic (env detection) to `helpers.ts`.

2023-04-28 10:01 UTC, soulBit approved these changes

2023-04-28 10:02 UTC, pietro-maximoff approved these changes

2023-05-05 11:46 UTC, merged