[AddressTablePagination] - add component
DistributedCollective/sovryn-dapp pull request #37
Opened 2022-10-18 09:56 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-680

2022-10-18 12:30 UTC, tiltom requested changes

2022-10-18 12:30 UTC, tiltom commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.tsx
> +  limit?: number;
```suggestion
  itemsPerPage?: number;
```

2022-10-18 12:30 UTC, tiltom commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.tsx
> +const DEFAULT_LIMIT = 5;
```suggestion
const DEFAULT_ITEMS_PER_PAGE = 5;
```

2022-10-18 12:30 UTC, tiltom commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.tsx
> +  const handleMoveRight = useCallback(() => {
```suggestion
  const handleClickNext = useCallback(() => {
```

2022-10-18 12:30 UTC, tiltom commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.tsx
> +  const handleMoveLeft = useCallback(() => {
```suggestion
  const handleClickPrevious = useCallback(() => {
```

2022-10-18 12:30 UTC, tiltom commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.test.tsx
> +  });
```suggestion
  it('renders AddressTablePagination', () => {
    const onPageChange = jest.fn();
    const { findAllByRole } = render(
      <AddressTablePagination onPageChange={onPageChange} />,
    );
    expect(findAllByRole('svg[data-icon="arrow-back"]')).toBeDefined();
  });
```

2022-10-18 12:30 UTC, tiltom commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.test.tsx
> +  it('does not allow to click on a disabled button', () => {
```suggestion
  it('does not allow to click Previous without clicking Next first', () => {
```

2022-10-18 12:30 UTC, tiltom commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.test.tsx
> +    render(<AddressTablePagination onPageChange={onPageChange} />);
```suggestion
    const { getAllByRole } = render(<AddressTablePagination onPageChange={onPageChange} />);
```

2022-10-18 12:30 UTC, tiltom commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.test.tsx
> +    screen.getAllByRole('button').forEach(element => {
```suggestion
    getAllByRole('button').forEach(element => {
```

2022-10-18 12:30 UTC, tiltom commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.stories.tsx
> +  onPageChange: noop,
I'd add here some `alert` or `console.log` to indicate what's happening (e.g. `console.log` with information about what items we should see).

2022-10-18 17:05 UTC, soulBit reviewed
Reviewed, no additional comments than the ones tiltom left

2022-10-19 07:36 UTC, creed-victor requested changes

2022-10-19 07:36 UTC, creed-victor commented on packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.tsx
> +  console.log(offset);
```suggestion
```

2022-10-19 07:41 UTC, creed-victor approved these changes

2022-10-19 08:07 UTC, Rickk137 approved these changes

2022-10-19 08:25 UTC, tiltom approved these changes

2022-10-19 10:49 UTC, merged