SOV-2294: Pull Zero fee rates directly from contracts - reimplementation
DistributedCollective/sovryn-dapp pull request #372
Opened 2023-05-05 14:08 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-2295

2023-05-11 10:09 UTC, Rickk137 requested changes

2023-05-11 10:09 UTC, Rickk137 commented on apps/frontend/src/app/5_pages/ZeroPage/utils/trove-manager.ts
> +export const getLiquityBaseParams = async (): Promise<ILiquityBaseParams> => {
I think this function should not be in this file. Maybe create another file?

2023-05-11 10:09 UTC, Rickk137 commented on apps/frontend/src/app/5_pages/ZeroPage/utils/trove-manager.ts
> +    return params;
```
cachedParams = {
      minBorrowingFeeRate,
      maxBorrowingFeeRate,
    };
    return cachedParams;
```

2023-05-11 11:06 UTC, tiltom requested changes

2023-05-11 11:06 UTC, tiltom commented on apps/frontend/src/app/5_pages/ZeroPage/hooks/useLiquityBaseParams.ts
> +  const [liquityBaseParams, setLiquityBaseParams] = useState({
```suggestion
  const [liquityBaseParams, setLiquityBaseParams] = useState<<ILiquityBaseParams>>({
```
`minBorrowingFeeRate` and `maxBorrowingFeeRate` have an incorrect type (`any`) without this.

2023-05-11 11:06 UTC, tiltom commented on apps/frontend/src/app/5_pages/ZeroPage/utils/trove-manager.ts
> +export const getLiquityBaseParams = async (): Promise<ILiquityBaseParams> => {
Exactly, this is not the place for this function. If you won't figure out a better location, I'd propose creating `index.ts` file in the current folder (`utils`) and placing it there.

2023-05-12 07:10 UTC, tiltom requested changes

2023-05-12 07:10 UTC, tiltom commented on apps/frontend/src/app/5_pages/ZeroPage/types.ts
> +export interface ILiquityBaseParams {
```suggestion
export type LiquityBaseParams {
```
Always use `type` if possible.

2023-05-12 07:10 UTC, tiltom commented on apps/frontend/src/app/5_pages/ZeroPage/utils/index.ts
> +    console.error(error);
```suggestion

```

2023-05-12 13:33 UTC, tiltom approved these changes

2023-05-16 13:30 UTC, merged