SOV-2234: LOC max debt and collateral loading
DistributedCollective/sovryn-dapp pull request #373
Opened 2023-05-09 10:47 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-2234

2023-05-11 11:33 UTC, tiltom requested changes

2023-05-11 11:33 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
> +      return Decimal.from(0);
```suggestion
      return Decimal.ZERO;
```

2023-05-11 11:33 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
> +      return Decimal.from(0);
```suggestion
      return Decimal.ZERO;
```

2023-05-11 11:33 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
> +        ? Decimal.from(0)
```suggestion
        ? Decimal.ZERO
```

2023-05-11 11:33 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
> +      return Decimal.from(0);
```suggestion
      return Decimal.ZERO;
```

2023-05-11 11:33 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/hooks/useZeroData.ts
> +      setIsLoading(false);
```suggestion

      setIsLoading(false);
      
```

2023-05-11 11:33 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/hooks/useZeroData.ts
>        const { ethers } = await getZeroProvider();
```suggestion
      setIsLoading(true);
      
      const { ethers } = await getZeroProvider();
      
```

2023-05-12 06:59 UTC, tiltom approved these changes

2023-05-12 14:57 UTC, soulBit approved these changes

2023-05-16 13:33 UTC, merged