SOV-2478: Documentation for Atoms in Gitbook (part 2)
DistributedCollective/sovryn-dapp pull request #401
Opened 2023-06-02 20:38 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-2478
fixes in this PR:
 - move Toggle component to Atoms section
 - fix broken "All Variations" section in the Input component

2023-06-06 07:58 UTC, creed-victor approved these changes

2023-06-06 10:06 UTC, soulBit requested changes

2023-06-06 10:06 UTC, soulBit commented on packages/ui/src/1_atoms/HealthBar/HealthBar.stories.tsx
> +    description: 'The data attribute to apply to the bar',
```suggestion
    description: 'The data id to apply as HTML attribute to this component instance. This should be unique per component instance on the page',
```

Please update to the suggested, and you can also reuse this for any other dataAttribute props we have in other components (saves having to customise it each time)

2023-06-06 10:06 UTC, soulBit commented on packages/ui/src/1_atoms/Input/Input.stories.tsx
> +    description: 'Whether the input is invalid',
```suggestion
    description: 'Whether the input is invalid. When set to true the error state styling and behaviour will be triggered on the input',
```

2023-06-06 10:06 UTC, soulBit commented on packages/ui/src/1_atoms/Input/Input.stories.tsx
> +    description: 'The onChange handler for the input',
```suggestion
    description: 'The onChange handler for the input, triggered whenever the input's value changes',
```

2023-06-06 10:06 UTC, soulBit commented on packages/ui/src/1_atoms/Icon/Icon.stories.tsx
> +    options: [
Can we pull these dynamically from `SizeProp`?

2023-06-06 10:06 UTC, soulBit commented on packages/ui/src/1_atoms/Input/Input.stories.tsx
> +    description: 'The debounce time in ms',
```suggestion
    description: 'The debounce time in milliseconds',
```

2023-06-06 10:06 UTC, soulBit commented on packages/ui/src/1_atoms/Lottie/Lottie.stories.tsx
> +    description: 'Set the number of times to loop the animation',
```suggestion
    description: 'Set the number of times to loop the animation. Loops indefinitely when set to "true"',
```

2023-06-06 10:06 UTC, soulBit commented on packages/ui/src/1_atoms/Paragraph/Paragraph.stories.tsx
> +      'The content of the paragraph. Can be text, other components, or HTML elements',
```suggestion
      'The content of the paragraph. Can be text, other components, or HTML elements. Underlying DOM element is a Paragraph tag so children should be compliant with this',
```

2023-06-06 11:12 UTC, pietro-maximoff commented on packages/ui/src/1_atoms/Icon/Icon.stories.tsx
> +    options: [
The SizeProp type itself - its a fixed set of string values and I created a separate array to hold those values and refer to them.

2023-06-08 10:29 UTC, soulBit commented on packages/ui/src/1_atoms/Icon/Icon.stories.tsx
> +    options: [
ah I see, we don't actually support all sizes then? from the Icon component code it appears like we do

2023-06-08 15:10 UTC, soulBit approved these changes

2023-06-09 09:17 UTC, soulBit approved these changes

2023-06-09 09:18 UTC, merged