SOV-2445: Create documentation for Atoms in Gitbook (part 1)
DistributedCollective/sovryn-dapp pull request #409
Opened 2023-06-13 12:10 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-2445

2023-06-13 16:27 UTC, pietro-maximoff requested changes

2023-06-13 16:27 UTC, pietro-maximoff commented on packages/ui/src/1_atoms/Button/Button.stories.tsx
> +
missing description for `hrefExternal` and `href` props

2023-06-13 16:27 UTC, pietro-maximoff commented on packages/ui/src/1_atoms/Checkbox/Checkbox.stories.tsx
> +};
missing description for `checked` prop

2023-06-13 16:27 UTC, pietro-maximoff commented on packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.stories.tsx
> +};
missing description for `weight` prop

2023-06-13 16:27 UTC, pietro-maximoff commented on packages/ui/src/1_atoms/Heading/Heading.stories.tsx
>  export const All = () => (
missing description for the details on the `All` page

2023-06-14 11:44 UTC, Rickk137 commented on packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.stories.tsx
> +};
the weight is not actually used for the component. It's used in ErrorsList component to set the priority

2023-06-14 11:57 UTC, pietro-maximoff approved these changes

2023-06-20 10:16 UTC, merged