SOV-2525: History table v1.2 updates
DistributedCollective/sovryn-dapp pull request #412
Opened 2023-06-16 09:56 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-2525

2023-06-18 14:17 UTC, Rickk137 requested changes

2023-06-18 14:17 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/LOCHistory/components/CollateralSurplusFrame/CollateralSurplusHistoryFrame.tsx
> +  onChangeLOCHistory,
This can stay in the parent component and receive the select as children to render next to the export file.

2023-06-18 14:17 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/LOCHistory/LOCHistory.tsx
> +        />
pass as prop or children:
`<Select
          value={selectedHistoryType}
          onChange={onChangeLOCHistory}
          options={locHistoryOptions}
        />`

2023-06-18 14:17 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/LOCHistory/LOCHistory.tsx
> +        />
pass as prop or children:
`<Select
          value={selectedHistoryType}
          onChange={onChangeLOCHistory}
          options={locHistoryOptions}
        />`

2023-06-18 14:17 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/LOCHistory/components/CollateralSurplusFrame/CollateralSurplusHistoryFrame.tsx
> +          options={locHistoryOptions}
the select should have a min width, to prevent export button jumping to the right when switching option

2023-06-18 14:17 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/LOCHistory/types.ts
> +};
i think the file name should change to LOCHistory.types

2023-06-18 14:17 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/LOCHistory/utils.ts
> +];
i think the file name should change to LOCHistory.utils

2023-06-19 12:17 UTC, Rickk137 approved these changes

2023-06-19 12:17 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/LOCHistory/components/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +        /> */}
this can be removed

2023-06-20 12:22 UTC, creed-victor approved these changes

2023-06-20 12:22 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/LOCHistory/LOCHistory.types.ts
> +};
You could use `React.PropsWithChildren` type instead of this

2023-06-20 12:22 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/LOCHistory/components/TransactionHistoryFrame/TransactionHistoryFrame.tsx
> +export const TransactionHistoryFrame: FC<LOCHistoryProps> = ({ children }) => {
```suggestion
export const TransactionHistoryFrame: FC<PropsWithChildren> = ({ children }) => {
```

2023-06-28 15:04 UTC, merged