feat: simple table component
DistributedCollective/sovryn-dapp pull request #42
Opened 2022-10-20 10:50 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-140
https://sovryn.atlassian.net/browse/SOV-676

2022-10-20 12:04 UTC, creed-victor approved these changes

2022-10-22 07:15 UTC, pietro-maximoff requested changes

2022-10-22 07:15 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/SimpleTable/SimpleTable.tsx
> +};
```suggestion
}) => (
  <div
    className={classNames(
      styles.simpleTable,
      {
        [styles.withBorder]: border,
      },
      className,
    )}
    data-layout-id={dataLayoutId}
  >
    {children}
  </div>
);
```

2022-10-22 07:15 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/SimpleTable/components/SimpleTableRow/SimpleTableRow.tsx
> +};
```suggestion
}) => (
  <div
    className={classNames(styles.row, className)}
    data-layout-id={dataLayoutId}
  >
    <span>{label}</span>
    <span className={styles.value}>{value}</span>
  </div>
);
```

2022-10-24 10:00 UTC, pietro-maximoff approved these changes

2022-10-25 07:01 UTC, LunaSov approved these changes

2022-10-25 10:01 UTC, merged