SOV-2493: Convert update v1 transaction history
DistributedCollective/sovryn-dapp pull request #426
Opened 2023-06-28 09:43 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-2493

2023-06-28 13:34 UTC, tiltom requested changes

2023-06-28 13:34 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/ConvertHistory.tsx
> +  const selectComponent = useMemo(
```suggestion
  const SelectComponent = useMemo(
```
It's a component so it should start with a capital letter.

2023-06-28 13:34 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/ConvertHistory.tsx
> +        onChange={(value: ConvertHistoryType) => setSelectedHistoryType(value)}
```suggestion
        onChange={setSelectedHistoryType}
```

2023-06-28 13:34 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/ConvertHistory.utils.tsx
> +export const convertHistoryOptions = [
This doesn't belong to `utils` but to `constants`. Delete this file, rename the const to `CONVERT_HISTORY_OPTIONS` and move it to `ConvertHistory.constants`.

2023-06-28 13:34 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/AmmConversionsHistoryFrame/AmmConversionsHistoryFrame.tsx
> +export const AmmConversionsHistoryFrame: React.FC<PropsWithChildren> = ({
All conversions history frames components are almost identical. They just differ in a few things. Extract all the common functionality and the render method to `BaseConversionsHistoryFrame` and pass the different things via props/util methods/custom hooks.

2023-06-28 13:34 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/AmmConversionsHistoryFrame/AmmConversionsHistoryFrame.utils.tsx
> +export const columnsConfig = [
Move it to `constants` file and rename to `COLUMNS_CONFIG`.

2023-06-28 13:34 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/MyntConversionsHistoryFrame/MyntConversionsHistoryFrame.utils.tsx
> +    cellRenderer: (item: Conversion) => (
Move it to `constants` file and rename to `COLUMNS_CONFIG`.

2023-06-28 13:34 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/TransactionIdRenderer/TransactionIdRenderer.tsx
>    const chain = chains.find(chain => chain.id === defaultChainId);
This can be moved above the component.

2023-06-28 13:34 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/ZeroConversionsHistoryFrame/ZeroConversionsHistoryFrame.utils.tsx
> +export const columnsConfig = [
Move it to `constants` file and rename to `COLUMNS_CONFIG`.

2023-06-28 15:29 UTC, tiltom requested changes

2023-06-28 15:29 UTC, tiltom commented on apps/frontend/src/app/2_molecules/TransactionIdRenderer/TransactionIdRenderer.tsx
> +  const chain = chains.find(chain => chain.id === defaultChainId);
Move it above the component.

2023-06-28 15:29 UTC, tiltom commented on apps/frontend/src/app/2_molecules/TransactionIdRenderer/TransactionIdRenderer.tsx
> +      dataAttribute="conversion-history-address-id"
This looks weird, I'd expect something like `conversion-history-tx-hash`.

2023-06-28 15:29 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/AmmConversionsHistoryFrame/AmmConversionsHistoryFrame.tsx
> +        <Pagination
Why do you need to pass `Pagination` as a prop? If it's only because of `setPage` then extract `Pagination` and `onPageChange` to `BaseConversionsHistoryFrame` and only pass `setPage` as a prop.

2023-06-28 15:29 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/MyntConversionsHistoryFrame/MyntConversionsHistoryFrame.constants.tsx
>    const isIncomingTransaction = item.type === ConversionType.Incoming; // bAsset -> mAsset
Move `sentAmountRenderer` and `receivedAmountRenderer` back to utils, only `COLUMNS_CONFIG` belongs to constants.

2023-06-28 15:29 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/AmmConversionsHistoryFrame/AmmConversionsHistoryFrame.constants.tsx
> +const renderConversionFee = (swap: Swap) => (
This belongs to utils, only `COLUMNS_CONFIG` should be in constants.

2023-06-28 15:29 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/MyntConversionsHistoryFrame/MyntConversionsHistoryFrame.tsx
> +          dataAttribute="amm-conversions-history-table"
This is `MyntConversionsHistoryFrame` so I believe it's not correct.

2023-06-28 15:29 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/MyntConversionsHistoryFrame/MyntConversionsHistoryFrame.tsx
> +          dataAttribute="amm-conversions-history-pagination"
This is `MyntConversionsHistoryFrame` so I believe it's not correct.

2023-06-28 15:29 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/ZeroConversionsHistoryFrame/ZeroConversionsHistoryFrame.constants.tsx
> +const renderRedemptionFee = (redemption: Redemption) => (
This function belongs to utils.

2023-06-29 11:14 UTC, pietro-maximoff approved these changes

2023-06-29 12:42 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/AmmConversionsHistoryFrame/AmmConversionsHistoryFrame.utils.tsx
> +    value={swap.conversionFee || '0'}
Spoke with Light, you will need to add `conversionFee` and `protocolFee` as we wan't to show total fee as conversion fee

2023-06-29 13:47 UTC, tiltom approved these changes

2023-07-05 21:08 UTC, merged