SOV-2612: New Rewards page - Stability pool and Staking rewards
DistributedCollective/sovryn-dapp pull request #441
Opened 2023-07-11 13:06 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-2612

2023-07-12 09:33 UTC, tiltom requested changes

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +  const claimLocked = stabilityClaimLocked || rewardsLocked;
```suggestion
  const claimLocked = useMemo(
    () =>
      checkMaintenance(States.REWARDS_FULL) ||
      checkMaintenance(States.ZERO_STABILITY_CLAIM),
    [States.REWARDS_FULL, States.ZERO_STABILITY_CLAIM, checkMaintenance],
  );
```
You don't use `rewardsLocked` and `stabilityClaimLocked` anywhere except `claimLocked`. I don't mind them for the readability so you can keep them if you want but at least use `useMemo` in `claimLocked`.

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +            dataAttribute="rewards-amount"
```suggestion
            dataAttribute="stability-subsidies-amount"
```

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +            dataAttribute="rewards-withdraw"
```suggestion
            dataAttribute="stability-subsidies-withdraw"
```

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +            dataAttribute="rewards-amount"
```suggestion
            dataAttribute="stability-rewards-amount"
```

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +              dataAttribute="rewards-withdraw"
```suggestion
              dataAttribute="stability-rewards-withdraw"
```

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +                dataAttribute="rewards-transfer-to-loc"
```suggestion
                dataAttribute="stability-rewards-transfer-to-loc"
```

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +            {isOpenTroveExists && Number(amount) > 0 && signer && (
```suggestion
            {isOpenTroveExists && !amount.isZero() && signer && (
```
`amount` is `Decimal` so casting it to `Number` is unnecessary.

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +            onClick={handleWithdraw}
If you withdraw subsidies, does it withdraw rewards as well (and vice versa)? If so, don't we need some tooltip or something to indicate that? Run that by @john-light pls.

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +          rowTitle={rows => rows.type}
This is not correct, it should show the amount in the title according to the design and the expanded version should look a bit different as well (I am not sure if that's easily possible, if not, just change the title and have a call with Fineline so she can adjust the design to match the implementation).

Design:
<img width="461" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/4a43bab2-c200-4835-b3d1-1195af1d387d">

Implementation:
<img width="757" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/a0954b42-64ee-422a-842a-1af1e6eee84d">

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
> +        type: t(translations.rewardPage.stabilityPool.stabilitySubsidies),
It should be `Staking subsidies`, not `Stability subsidies`.

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
> +  const rows = useMemo(() => {
I see only 5 rewards types but there are 6 in the [PRD](https://docs.google.com/document/d/1oMqMHZw0K6muZFV621tPn-lv92qL3Vo_U2kcUy6Dr5U/edit), check it with @john-light if you believe there's a mistake in the PRD or fix the implementation.

Also, there's no indication which types are the legacy ones (but it should be according to the design).

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
> +          rowTitle={row => `${row.type}-${getTokenDisplayName(row.token)}`}
Mobile rows don't look exactly as in the design (the same situation as in the Stability pool rewards) - have a call with Fineline and make sure the design and implementation match (try to find some compromise in case it's hard to customize the mobile content).

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/constants.tsx
> +
Rename the file to `StabilityPool.constants.tsx`.

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/components/WithdrawLiquidFee/WithdrawLiquidFee.tsx
> +  }, [amountToClaim, tokenBalance]);
```suggestion
  const hasTokenBalance = useMemo(
    () => decimalic(tokenBalance).gte(amountToClaim),
    [amountToClaim, tokenBalance],
  );
```

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/constants.tsx
> +
Rename the file to `Staking.constants.tsx`.

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetFeesEarned.ts
> +    '0xeabd29be3c3187500df86a2613c6470e12f2d77d',
Create a const `DEFAULT_RBTC_DUMMY_ADDRESS` and use it instead.

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetLiquidSovClaimAmount.ts
> +export const useGetLiquidSovClaimAmount = () => {
The UI shows me I have `0 SOV` liquid but withdraw button is enabled. Why is that? 
<img width="717" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/b17440e1-c275-438b-b827-c682c8a9360a">

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetLiquidSovClaimAmount.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Why do you need this?

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetNextPositiveCheckpoint.ts
> +    const tokenContract = await getContract(token, 'tokens', getRskChainId());
Can't you just use `getTokenContract`?

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetTotalTokenCheckpoints.ts
> +    const tokenContract = await getContract(token, 'tokens', getRskChainId());
```suggestion
    const tokenContract = await getTokenContract(token);
```

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/constants/general.ts
> +export const MAX_PROCESSABLE_CHECKPOINTS_RBTC = 33;
This is not used anywhere, is that correct?

2023-07-12 09:33 UTC, tiltom commented on apps/frontend/src/locales/en/translations.json
> +            "stakingRevenue": "Staking revenue",
This shouldn't be here as it's not in Stability pool section.

2023-07-17 03:59 UTC, john-light commented on apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
> +            onClick={handleWithdraw}
> If you withdraw subsidies, does it withdraw rewards as well (and vice versa)?

yes

> If so, don't we need some tooltip or something to indicate that?

We haven't considered that for this release, but could be good to add in the future. and/or we think about how we can combine the withdraw buttons to make it clear clicking one will withdraw both reward types.

2023-07-17 10:17 UTC, closed without merging