SOV-2738: Develop D2 Lend page
DistributedCollective/sovryn-dapp pull request #458
Opened 2023-07-24 08:27 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-2738
Note: The chart shows not correct data for now

2023-07-25 13:16 UTC, soulBit requested changes

2023-07-25 13:16 UTC, soulBit commented on apps/frontend/src/app/3_organisms/Header/Header.constants.tsx
> +    submenu: [
The dropdown seems a bit weird in the mobile menu, perhaps we should just show all options listed under a header item similar to Sovryn Alpha options (or similar to D1 mobile menu)

2023-07-25 13:16 UTC, soulBit commented on apps/frontend/src/app/5_pages/LendPage/components/AcceptedCollateral/AcceptedCollateral.tsx
> +              {index !== COLLATERAL_ITEMS_TO_SHOW - 1 && <span>, </span>}
Small thing, but spec says there should be a comma after the last asset name so that the last part reads:
`, and more`

2023-07-25 13:16 UTC, soulBit commented on apps/frontend/src/locales/en/translations.json
> +            "avaliable": "Avaliable",
```suggestion
            "available": "Available",
```

2023-07-25 13:16 UTC, soulBit commented on apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameDetails/LendFrameDetails.tsx
> +          label={t(translations.lendPage.table.avaliable)}
```suggestion
          label={t(translations.lendPage.table.available)}
```

2023-07-25 13:16 UTC, soulBit commented on apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.tsx
> +  }, [mockData, chartOptions, asset]);
I think you need a disposal function here to get rid of the current chart when this component unrenders - not sure exactly how I triggered it but I received this error:
![image](https://github.com/DistributedCollective/sovryn-dapp/assets/765825/63b551c4-a2a7-4654-ad58-d784cd5ec4ee)

2023-07-25 13:16 UTC, soulBit commented on apps/frontend/src/router.tsx
> +      },
Move this part next to lines 60-63 so that all the Earn content is together

2023-07-25 17:18 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/Header/Header.constants.tsx
> +    submenu: [
as I understand, we will do this in a separate task that has already been created

2023-07-26 09:48 UTC, soulBit approved these changes

2023-08-04 12:05 UTC, creed-victor commented
changes already at #479

2023-08-04 12:05 UTC, closed without merging