SOV-2739: Develop D2 Lend page - Lend modal
DistributedCollective/sovryn-dapp pull request #459
Opened 2023-07-24 10:17 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-2739

2023-07-26 06:46 UTC, pietro-maximoff requested changes

2023-07-26 06:46 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/LendPage/components/LendModal/CurrentStats.tsx
> +          <Tooltip content={acceptedList} className={styles.assets}>
```suggestion
          <Tooltip trigger={TooltipTrigger.click} content={acceptedList} className={styles.assets}>
```

2023-07-26 06:46 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/LendPage/hooks/useHandleLending.ts
> +      console.log({
if you don't need this info pls remove it

2023-07-26 06:46 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/LendPage/components/LendModal/LendingForm.tsx
> +      () => state.poolTokenContract.nextSupplyInterestRate(amount),
after changing the destination branch of this PR to [`SOV-2738: Develop D2 Lend page`] PR you can just use a hook from `apps/frontend/src/app/5_pages/LendPage/hooks/useGetNextSupplyInterestRate.ts`

2023-08-04 12:04 UTC, creed-victor commented
changes already at #479

2023-08-04 12:04 UTC, closed without merging