SOV-2805: Staking and Rewards page UX updates
DistributedCollective/sovryn-dapp pull request #469
Opened 2023-07-28 13:34 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-2805

2023-07-28 14:20 UTC, tiltom requested changes
There's no top-banner on the Staking page.

Design:
<img width="1691" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/689bb57e-a93f-4cfc-b151-17034a7ad77b">

Implementation:
<img width="2531" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/6adf05ce-8e0a-4e95-8f91-8f8992ade38f">

2023-07-28 14:20 UTC, tiltom commented on apps/frontend/src/app/3_organisms/StakeForm/components/AddStakeForm/AddStakeForm.tsx
> +          label={t(translations.stakePage.stakeForm.votingPowerIncrease)}
Delete `stakeForm.votingPowerReceived` from `translations` as it's not used anywhere.

2023-07-28 14:20 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
> +          <Banner
The banners should have `Learn more` links.

Design:
<img width="507" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/49f71aa1-a8fa-4179-9fb0-e942dcf7de71">

Implementation:
<img width="444" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/626c21f6-e76e-4581-9b2e-e7f71a687e41">

2023-07-31 08:28 UTC, Rickk137 commented
> There's no top-banner on the Staking page.
> 
> Design: <img alt="image" width="1691" src="https://user-images.githubusercontent.com/14878713/256847235-689bb57e-a93f-4cfc-b151-17034a7ad77b.png">
> 
> Implementation: <img alt="image" width="2000" src="https://user-images.githubusercontent.com/14878713/256847364-6adf05ce-8e0a-4e95-8f91-8f8992ade38f.png">

The banner can be closed on mobile. if you do so you won't see it any more.

2023-08-01 13:37 UTC, tiltom approved these changes

2023-08-01 13:37 UTC, tiltom commented on apps/frontend/src/locales/en/translations.json
> +            "description": "Participate in Sovryn's governance and revenue, earn up to 26.8% APY paid in bitcoin",
Verify with @john-light if this number should be fetched dynamically or if a static value is enough.

2023-08-02 18:32 UTC, john-light commented on apps/frontend/src/locales/en/translations.json
> +            "description": "Participate in Sovryn's governance and revenue, earn up to 26.8% APY paid in bitcoin",
It should be dynamic, based on the same method used to get the staking APY on the staking page.

2023-08-10 09:37 UTC, closed without merging