feat: add multiple theme support
DistributedCollective/sovryn-dapp pull request #5
Opened 2022-08-23 15:11 UTC by Rickk137

2022-08-29 12:38 UTC, tiltom requested changes

2022-08-29 12:38 UTC, tiltom commented on apps/frontend/src/app/5_pages/App.tsx
> +enum Theme {
Rename it to `AppTheme`, create a new file (e.g. `tailwind.ts`) in `types` folder and move it there.

2022-08-31 08:32 UTC, tiltom requested changes

2022-08-31 08:32 UTC, tiltom commented on apps/frontend/src/app/5_pages/App.tsx
>    return (
```suggestion
  const { handleThemeChange } = useTheme();
  
  return (
```

2022-08-31 08:32 UTC, tiltom commented on apps/frontend/src/hooks/useTheme.ts
> +  const handleThemeChange = (theme: AppTheme) => {
Use `useCallback`.

2022-08-31 08:32 UTC, tiltom commented on apps/frontend/src/hooks/useTheme.ts
> +    console.log(theme)
```suggestion

```

2022-08-31 13:55 UTC, tiltom approved these changes

2022-08-31 13:55 UTC, tiltom commented
It looks good but deployment is failing, pls fix it @Rickk137 .

2022-09-05 08:25 UTC, tiltom approved these changes

2022-09-05 16:00 UTC, pietro-maximoff approved these changes

2022-09-07 11:51 UTC, merged