SOV-2747: Finalize Borrow page
DistributedCollective/sovryn-dapp pull request #501
Opened 2023-08-09 08:41 UTC by tiltom

Resolves https://sovryn.atlassian.net/browse/SOV-2747

2023-08-10 12:04 UTC, soulBit requested changes

2023-08-10 12:04 UTC, soulBit commented on apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.tsx
> +import { generateRowTitle } from '../../../LendPage/components/LendFrame/LendFrame.utils';
Not for this specific line but I can't find any changes in the BorrowPage file to target - the Loans table should only appear when user has a connected wallet (see section 2 and 5 of spec)

2023-08-10 12:04 UTC, soulBit commented on apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.constants.tsx
> +      <div>{MINIMUM_COLLATERAL_RATIO_LENDING_POOLS.mul(100).toString()}%</div>
This should be 115% as it's different to the min collateral ratio for borrowing - see CEKs comment here:
`The maintenanceMargin is 15% for all so the min CR is 115% to avoid partial liquidations.`
https://discord.com/channels/729675474665603133/1138544013725667478/1138544013725667478

Please ask Light to update spec to reflect this as well

2023-08-10 12:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.constants.tsx
> +      <div>{MINIMUM_COLLATERAL_RATIO_LENDING_POOLS.mul(100).toString()}%</div>
@john-light will you update the PRD pls?

2023-08-10 13:42 UTC, soulBit approved these changes

2023-08-11 01:48 UTC, john-light commented on apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.constants.tsx
> +      <div>{MINIMUM_COLLATERAL_RATIO_LENDING_POOLS.mul(100).toString()}%</div>
@tiltom  can you please leave a comment on the PRD where you think it needs to be updated?

2023-08-11 08:17 UTC, tiltom commented on apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.constants.tsx
> +      <div>{MINIMUM_COLLATERAL_RATIO_LENDING_POOLS.mul(100).toString()}%</div>
@john-light I was looking at the PRD and it was fine, sorry for the false alarm.

2023-08-11 13:05 UTC, soulBit approved these changes

2023-08-23 07:25 UTC, merged