feat: FormGroup component
DistributedCollective/sovryn-dapp pull request #51
Opened 2022-10-25 09:44 UTC by Rickk137

2022-10-25 12:12 UTC, creed-victor requested changes

2022-10-25 12:12 UTC, creed-victor commented on packages/ui/src/2_molecules/FormGroup/FormGroup.tsx
> +      <span data-layout-id="error-message" className={styles.errorLabel}>
```suggestion
      <span data-layout-id={`${dataLayoutId}__error-message`} className={styles.errorLabel}>
```

2022-10-27 07:50 UTC, creed-victor approved these changes

2022-10-27 12:16 UTC, tiltom requested changes

2022-10-27 12:16 UTC, tiltom commented on packages/ui/src/2_molecules/FormGroup/FormGroup.module.css
> +  @apply text-xs font-medium;
```suggestion
  @apply font-medium;
```
Unnecessary.

2022-10-27 12:16 UTC, tiltom commented on packages/ui/src/2_molecules/FormGroup/FormGroup.stories.tsx
> +export const _FormGroup = Template.bind({});
```suggestion
export const Basic = Template.bind({});
```

2022-10-27 12:16 UTC, tiltom commented on packages/ui/src/2_molecules/FormGroup/FormGroup.stories.tsx
> +export const _FormGroupInvalid = Template.bind({});
```suggestion
export const Invalid = Template.bind({});
```

2022-10-27 12:16 UTC, tiltom commented on packages/ui/src/2_molecules/FormGroup/FormGroup.stories.tsx
> +export const _FormGroupButton = Template.bind({});
```suggestion
export const WithButton = Template.bind({});
```

2022-10-27 12:16 UTC, tiltom commented on packages/ui/src/2_molecules/FormGroup/FormGroup.test.tsx
> +
Look at our other tests, you should have `describe` (https://jestjs.io/docs/api#describename-fn) first with the name of the component and then test cases.

2022-10-27 12:16 UTC, tiltom commented on packages/ui/src/2_molecules/FormGroup/FormGroup.test.tsx
> +      subtext={'subtext'}
```suggestion
      label="label"
      subtext="subtext"
```

2022-10-27 12:16 UTC, tiltom commented on packages/ui/src/2_molecules/FormGroup/FormGroup.test.tsx
> +      label={'label'}
```suggestion
      label="label"
```

2022-10-27 12:16 UTC, tiltom commented on packages/ui/src/2_molecules/FormGroup/FormGroup.tsx
> +  //You need to pass invalid={!!errorLabel} to the children if you want the invalid style applied there
```suggestion

```
I don't think we need this comment.

2022-10-28 09:49 UTC, soulBit approved these changes
Looking good apart from subtext styling which seemed a bit off - I synced with Gilad on this and updated styling/storybook examples

2022-10-31 07:45 UTC, LunaSov approved these changes

2022-10-31 10:21 UTC, merged