Feat/sov 568 d 2 radio button component implementation
DistributedCollective/sovryn-dapp pull request #55
Opened 2022-10-26 09:35 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-568
https://sovryn.atlassian.net/browse/SOV-710

2022-10-27 10:10 UTC, Rickk137 commented
@pietro-maximoff could you add ``RadioButton`` and ``RadioButonGroup`` to ``2_molecules/index.tsx``

2022-10-27 10:18 UTC, Rickk137 commented
<img width="672" alt="Screen Shot 2022-10-27 at 1 48 23 PM" src="https://user-images.githubusercontent.com/25097709/198259261-15aaa9c7-37f2-4d1f-a787-7aa7c5624c99.png">
disabled is not showing in the story book for QA to test

2022-10-27 10:22 UTC, Rickk137 commented
<img width="591" alt="Screen Shot 2022-10-27 at 1 52 02 PM" src="https://user-images.githubusercontent.com/25097709/198259991-80c84454-4e81-410f-a5ed-c7655ad40abe.png">
The labelInfo doesn't get the disabled style

2022-10-27 10:31 UTC, Rickk137 requested changes

2022-10-27 10:31 UTC, Rickk137 commented on packages/ui/src/2_molecules/RadioButtonGroup/RadioButtonGroup.tsx
> +            value={label}
I think you should add value to the ``RadioButtonOption`` and use it here

2022-10-27 10:31 UTC, Rickk137 commented on packages/ui/src/2_molecules/RadioButtonGroup/RadioButtonGroup.tsx
> +            defaultChecked={index === 0}
How about getting it as prop for RadioButtonGroupProps? (and if it was undefined none of the options be pre selected)

2022-10-27 10:31 UTC, Rickk137 commented on packages/ui/src/2_molecules/RadioButton/RadioButton.stories.tsx
> +  </>
``` <RadioButton {...args} />```

2022-10-28 10:10 UTC, creed-victor approved these changes

2022-10-28 11:06 UTC, pietro-maximoff commented
@soulBit thanks for checking, and regarding the <legend> tag I think semantically it would be correct to use it instead of the <h3> tag, h3 is mainly used for content as I know. do you think it's better to leave it with h3?

2022-10-28 11:15 UTC, creed-victor approved these changes

2022-10-28 11:18 UTC, soulBit approved these changes

2022-10-31 10:19 UTC, LunaSov approved these changes

2022-10-31 10:23 UTC, merged