SOV-2799: reward claiming
DistributedCollective/sovryn-dapp pull request #550
Opened 2023-08-30 12:23 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-2799

2023-09-21 13:17 UTC, tiltom requested changes
@creed-victor I tried the `Withdraw all` functionality but `SOV` and `ZUSD` fees were not withdrawn, even though the tx was successful. Can you look into it? My testing address is `0xaaa5a190accbc50f4f9c130b5876521e4d5f9d6c` if needed.

 Tx: https://explorer.testnet.rsk.co/tx/0xe5f87e3d3ba41131bee08e14cee47660a69b05bc1dc9eeef35dd05b34635be08

<img width="818" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/58005428-a001-4022-8c59-2ecf5ff6c170">

2023-09-21 13:17 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
> +  const rows1 = useMemo(
```suggestion
  const rows = useMemo(
```

2023-09-21 13:17 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/components/WithdrawAllFees/WithdrawAllFees.tsx
> +type UserCheckpoint = {
You could extract it to `WithdrawAllFees.types.ts`.

2023-09-22 11:22 UTC, creed-victor commented
> @creed-victor I tried the `Withdraw all` functionality but `SOV` and `ZUSD` fees were not withdrawn, even though the tx was successful. Can you look into it? My testing address is `0xaaa5a190accbc50f4f9c130b5876521e4d5f9d6c` if needed.

This is how smart contract function works and it's expected. If user has a lot of tokens and checkpoints, they will have to send multiple transactions until all tokens/checkpoints are withdrawn.

2023-09-22 11:39 UTC, tiltom approved these changes

2023-09-29 12:07 UTC, soulBit approved these changes

2023-10-02 10:18 UTC, merged