SOV-3013: Voting - Next Steps modal
DistributedCollective/sovryn-dapp pull request #564
Opened 2023-09-06 11:13 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-3013

2023-09-06 15:05 UTC, soulBit requested changes
Looks good, just needs the close button for dialog enabled (point 11.a in PRD)

2023-09-07 07:48 UTC, pietro-maximoff requested changes

2023-09-07 07:48 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/StakePage/components/NextStepDialog/NextStepDialog.tsx
> +                <Heading className="text-gray-10 mb-2" type={HeadingType.h3}>
```suggestion
                <Heading className="text-gray-10 mb-2 leading-5 font-medium" type={HeadingType.h3}>
```

2023-09-07 07:48 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/StakePage/components/NextStepDialog/NextStepDialog.tsx
> +              <div className="bg-gray-70 min-w-[4.375rem] h-[4.375rem] rounded mr-4 text-sovryn-blue flex items-center justify-center">
```suggestion
              <div className="bg-gray-70 min-w-[4.375rem] h-[4.375rem] rounded mr-5 text-sovryn-blue flex items-center justify-center">
```

2023-09-08 08:23 UTC, pietro-maximoff approved these changes

2023-09-08 09:20 UTC, soulBit approved these changes

2023-10-04 13:52 UTC, merged