SOV-2754: Update token amount output component
DistributedCollective/sovryn-dapp pull request #571
Opened 2023-09-11 08:47 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-2754

2023-09-11 10:16 UTC, Rickk137 requested changes

2023-09-11 10:16 UTC, Rickk137 commented on apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
> +  }, []);
`const isValueBetweenZeroAndOne = useCallback((value: number) => value > 0 && value < 1, []);`

2023-09-11 10:16 UTC, Rickk137 commented on apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
> +  }, []);
i think this function should be moved to a util file

2023-09-11 10:16 UTC, Rickk137 commented on apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
> +  );
this function should be moved to a util file

2023-09-11 10:32 UTC, Rickk137 approved these changes

2023-09-12 08:17 UTC, creed-victor approved these changes

2023-09-12 13:34 UTC, merged