SOV-894: select component
DistributedCollective/sovryn-dapp pull request #58
Opened 2022-10-28 09:58 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-894

also changes dropdown component a little:

- add property for possibility to close dropdown when option is clicked
- add property for possibility to open dropdown option not inside of portal (so it would work in dialogs too)

2022-10-28 14:14 UTC, soulBit requested changes

2022-10-28 14:14 UTC, soulBit commented on packages/ui/src/2_molecules/Menu/components/MenuItem/MenuItem.module.css
> +      @apply text-gray-30 font-normal text-tiny inline-block leading-none pointer-events-none pointer-events-none;
```suggestion
      @apply text-gray-30 font-normal text-tiny inline-block leading-none pointer-events-none;
```

2022-10-28 14:14 UTC, soulBit commented on packages/ui/src/2_molecules/Select/Select.stories.tsx
> +// };
```suggestion

```

2022-10-28 15:15 UTC, pietro-maximoff requested changes

2022-10-28 15:15 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/Dropdown/Dropdown.module.css
> +  z-index: 9999;
```suggestion
  @apply absolute overflow-x-auto mt-1 transition-colors z-[9999];
```

2022-10-28 15:43 UTC, soulBit commented on packages/ui/src/2_molecules/index.ts
> +export * from './Select';
```suggestion
export * from './AddressTablePagination';
export * from './Select';
```

2022-10-28 15:45 UTC, soulBit approved these changes

2022-10-28 15:54 UTC, pietro-maximoff approved these changes

2022-11-01 11:34 UTC, LunaSov approved these changes

2022-11-01 12:47 UTC, merged