SOV-3010: Individual Proposal page
DistributedCollective/sovryn-dapp pull request #583
Opened 2023-09-18 08:17 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-3010
https://sovryn.atlassian.net/browse/SOV-2923

2023-09-18 15:20 UTC, creed-victor requested changes

2023-09-18 15:20 UTC, creed-victor commented on apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalViewButton/ProposalViewButton.tsx
> +  />
If `_blank` is expected, i think you should use hyperlink not button

2023-09-18 15:20 UTC, creed-victor commented on apps/frontend/src/app/5_pages/ProposalPage/hooks/useGetProposals.ts
> +  return { loading, proposal };
Use a subgraph query which actually queries for a single proposal by it's id, list is unnecessary for this page. You can then request additional fields that are needed here (like emittedBy.majorityPercentageVotes and etc)

2023-09-18 15:20 UTC, creed-victor commented on apps/frontend/src/utils/graphql/rsk/operations/getProposals.graphql
> +    proposer
```suggestion
```

create `getProposal` query which will include this instead

2023-09-19 11:11 UTC, creed-victor requested changes

2023-09-19 11:11 UTC, creed-victor commented on apps/frontend/src/utils/graphql/rsk/operations/getProposal.graphql
> +  proposals(where: { id: $id }) {
```suggestion
  proposal(id: $id) {
```

2023-09-19 11:11 UTC, creed-victor commented on apps/frontend/src/app/5_pages/ProposalPage/hooks/useGetProposalById.ts
> +  );
```suggestion
  const proposal = useMemo(
    () => data?.proposal as Proposal | undefined,
    [data],
  );
```

2023-09-19 19:45 UTC, pietro-maximoff requested changes

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/ProposalVotingResults/index.tsx
rename index.tsx -> ProposalVotingResults.tsx to be consistent with other components

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/ProposalPage/components/VoteTimer/VoteTimer.tsx
<img width="729" alt="tooltip" src="https://github.com/DistributedCollective/sovryn-dapp/assets/74987028/3f203a7b-c480-410a-a33b-5bd416050fe3">

In the design, we have a tooltip with Vote start and Vote end data, but in the PRD we don't have any info about it, so I believe its better to check in which way we will go (with a tooltip or without) @soulBit

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/ProposalPage/components/VoteTimer/VoteTimer.tsx
> +    return new Date((proposal.timestamp + secondsBetweenBlocks) * 1000);
```suggestion
    return new Date((proposal.timestamp + secondsBetweenBlocks) * MS);
```

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/ProposalPage/components/VoteTimer/VoteTimer.tsx
> +    autoStart: true,
you can remove this because by default it is set to true

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/ProposalPage/components/ExecutableDetails/ExecutableDetails.tsx
missed bg for past SIPs
<img width="924" alt="missedBG" src="https://github.com/DistributedCollective/sovryn-dapp/assets/74987028/c800cbfc-e9f3-4035-b43e-e873e0ac2685">

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/ProposalPage/components/ExecutableDetails/ExecutableDetails.tsx
> +                  dataAttribute="stability-pool-history-address-id"
```suggestion
                  dataAttribute="proposal-contract-address-id"
```

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.tsx
> +                  dataAttribute="stability-pool-history-address-id"
```suggestion
                  dataAttribute="proposal-proposer-address-id"
```

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.tsx
1) somewhere on this page we have errors in the console, regarding including `<div>` inside `<p>`, I believe its something inside of `<Paragraph>` component
<img width="1331" alt="consoleErrors" src="https://github.com/DistributedCollective/sovryn-dapp/assets/74987028/205101b6-fefb-4e9b-b91b-820da934e40c">

2) The mobile version is not optimized:
<img width="414" alt="mobile" src="https://github.com/DistributedCollective/sovryn-dapp/assets/74987028/c2cb57c8-89c9-42b5-a108-3f8b520ab4cb">

3) We are missing the `Your voting power` block which we have in design, but I can't find any info in PRD about it
<img width="878" alt="votingPowerBlock" src="https://github.com/DistributedCollective/sovryn-dapp/assets/74987028/fc39c558-bbed-4627-bcc0-062192f3999c">

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.tsx
> +            <Heading className="text-base sm:text-2xl font-medium">
we need to add `word-break: break-all;` or something like that to prevent this case:
<img width="1308" alt="titleError" src="https://github.com/DistributedCollective/sovryn-dapp/assets/74987028/59f51e36-f38e-481c-9f3a-5c7414627c70">

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/ProposalVotingResults/index.tsx
> +                    value: formatValue(majorityPercentageVotes, 3),
It is probably graphql issue and we need to double-check it
<img width="616" alt="weirdValue" src="https://github.com/DistributedCollective/sovryn-dapp/assets/74987028/1348855f-08b0-411e-a320-4b2f8eb8cbef">

2023-09-19 19:45 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/ProposalPage/components/ProposalInfo/ProposalInfo.tsx
> +};
```suggestion
export const ProposalInfo: FC<ProposalInfoProps> = ({ link, description }) => (
  <div className="bg-gray-90 px-6 pt-6 pb-3 rounded">
    <div className="flex">
      <Paragraph
        size={ParagraphSize.base}
        className="text-xs w-24 mb-3 text-gray-30"
      >
        {t(pageTranslations.discussionLink)}
      </Paragraph>
      {link && (
        <Paragraph size={ParagraphSize.base} className="text-xs">
          <a
            href={link}
            className="text-primary-20"
            target="_blank"
            rel="noreferrer"
          >
            {link}
          </a>
        </Paragraph>
      )}
    </div>

    <div className="flex">
      <Paragraph
        size={ParagraphSize.base}
        className="text-xs w-24 text-gray-30"
      >
        {t(pageTranslations.proposalText)}
      </Paragraph>
      <Paragraph size={ParagraphSize.base} className="text-xs">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{description}</ReactMarkdown>
      </Paragraph>
    </div>
  </div>
);
```

2023-09-19 20:22 UTC, pietro-maximoff requested changes

2023-09-19 20:22 UTC, pietro-maximoff commented on apps/frontend/src/app/3_organisms/ProposalVotingResults/index.tsx
> +            {t(translations.proposalVotingResults.inProgress)}
when proposal in progress, the title should be `In progress, Will succeed` or `In progress, Will be rejected`
<img width="348" alt="inProgress" src="https://github.com/DistributedCollective/sovryn-dapp/assets/74987028/3526e73a-255f-4269-bbae-bbf74c249ecc">

2023-09-20 10:05 UTC, Rickk137 commented
@soulBit  We are missing the Your voting power block which we have in design, but I can't find any info in PRD about it
![](https://user-images.githubusercontent.com/74987028/269080351-fc39c558-bbed-4627-bcc0-062192f3999c.png)

2023-09-20 10:36 UTC, soulBit commented on apps/frontend/src/app/5_pages/ProposalPage/components/VoteTimer/VoteTimer.tsx
leave it according to PRD for now, we'll create a separate story for confirming how this should work and implementation

2023-10-05 10:38 UTC, merged