chore: refactor data-layout-id prop names to constant
DistributedCollective/sovryn-dapp pull request #59
Opened 2022-10-28 13:42 UTC by soulBit

https://sovryn.atlassian.net/browse/SOV-861

2022-10-28 15:21 UTC, pietro-maximoff approved these changes
checked this code + checked locally

2022-10-28 16:10 UTC, creed-victor requested changes

2022-10-28 16:10 UTC, creed-victor commented on packages/ui/src/2_molecules/Tooltip/Tooltip.tsx
> +import { DATA_ATTRIBUTE } from '../../utils/constants';
should use `applyDataAttr` here too maybe?

2022-10-28 16:10 UTC, creed-victor commented on packages/ui/src/2_molecules/WalletContainer/WalletContainer.tsx
> +      {...{ [DATA_ATTRIBUTE]: dataLayoutId }}
```suggestion
      {...applyDataAttr(dataLayoutId)}
```

2022-10-31 11:19 UTC, creed-victor approved these changes

2022-10-31 11:20 UTC, merged