feat: ui components migration
DistributedCollective/sovryn-dapp pull request #6
Opened 2022-09-01 07:18 UTC by Rickk137

2022-09-02 11:56 UTC, tiltom requested changes
Pls go through all of the files in this PR and make sure you have correct formatting.

2022-09-02 11:56 UTC, tiltom commented on .prettierrc
> +{
Why did you add this file? We have our configs in packages and we use configuration from `eslint-config-custom`.

2022-09-02 11:56 UTC, tiltom commented on .vscode/extensions.json
> +{
This doesn't belong to the repo, it's probably just some local config for you. Don't commit it.

2022-09-02 11:56 UTC, tiltom commented on .vscode/launch.json
> +{
This doesn't belong to the repo, it's probably just some local config for you. Don't commit it.

2022-09-02 11:56 UTC, tiltom commented on .vscode/postcss-custom-data.json
> +{
This doesn't belong to the repo, it's probably just some local config for you. Don't commit it.

2022-09-02 11:56 UTC, tiltom commented on .vscode/settings.json
> +{
This doesn't belong to the repo, it's probably just some local config for you. Don't commit it.

2022-09-02 11:56 UTC, tiltom commented on packages/ui/.storybook/preview.js
> +  xs: "320px",
This formatting is not correct, when I format this file I get single quotes that are correct.

2022-09-02 14:12 UTC, tiltom requested changes

2022-09-02 14:12 UTC, tiltom commented on packages/ui/package.json
> +    "@fortawesome/fontawesome-svg-core": "^6.2.0",
I added a new rule (after a discussion with @soulBit and @creed-victor) regarding packages versioning: https://sovryn.monday.com/docs/2733202752?blockId=aebe8f4b-5e4a-4ef6-8967-503ce7a1bb30 . Pls, adjust the whole file.

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/1_atoms/Button/Button.tsx
> +}
Create a type file for the component (`Button.types.ts`) and extract it there.

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/1_atoms/Button/Button.tsx
> +  const onClickWhenAllowed = !disabled && !loading ? onClick : undefined;
```suggestion
  const onClickHandler = !disabled && !loading ? onClick : undefined;
```

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/1_atoms/Button/Button.tsx
> +  const onClickWhenAllowed = !disabled && !loading ? onClick : undefined;
Use `useMemo` as well.

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/1_atoms/Button/Button.tsx
> +Button.defaultProps = {
Do not use `defaultProps`, see https://sovryn.monday.com/docs/2733202752?blockId=8271db19-de51-4fd3-b6a0-88e3be3cb025 .

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/1_atoms/Icon/Icon.tsx
> +const SM = 'sm';
Move them to `Icon.types.ts`.

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/1_atoms/Icon/Icon.tsx
> +  }, [icon]);
```suggestion
  const isFaIcon = useMemo(() => !!icon && !!icon['prefix'], [icon]);
```

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/1_atoms/Icon/Icon.tsx
> +  }, [inline]);
```suggestion
  const inlineBlock = useMemo(() => inline ? 'inline-block' : 'block', [inline]);
```

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Dialog/dialog.module.css
> +
Rename the file to `Dialog.module.css`, make sure all of the components have proper file names.

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Dialog/types.ts
> +
Rename the file to `Dialog.types.ts`.

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Dropdown/Dropdown.tsx
> +  );
```suggestion
  const classNameComplete = useMemo(
    () => classNames(styles.button, color, className, {
      [styles.isOpen] : isOpen
    }),
    [color, className, isOpen],
  );
```

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Dropdown/Dropdown.tsx
> +  }, [onClose]);
```suggestion
  const useClickedOutside = useCallback(() => {
    setOpen(false);
    onClose?.();
  }, [onClose]);
```

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Dropdown/Dropdown.tsx
> +    }
```suggestion
    onOpen?.();
```

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Dropdown/types.ts
> +
Rename the file to `Dropdown.types.ts`.

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Dropdown/utils.ts
> +
Rename the file to `Dropdown.utils.ts`. Make sure that every file in this PR is named according to https://sovryn.monday.com/docs/2733202752?blockId=275525d0-9985-4644-8023-61b8ead7d005 .

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Menu/components/MenuItem/index.tsx
> +  //TODO: use IconComponents enum here instead, requires Icon Component to be done
What about this comment? `Icon` component is done.

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Menu/components/MenuSeparator/index.tsx
> +};
```suggestion
export const MenuSeparator: React.FC<MenuSeparatorProps> = ({
  className,
  text,
}) => <li className={classNames(styles.host, className)}>{text}</li>;
```

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Overlay/Overlay.tsx
> +};
Extract to the types file.

2022-09-02 14:12 UTC, tiltom commented on packages/ui/src/2_molecules/Overlay/Overlay.tsx
> +      }
```suggestion
        onBlur?.(event);
```

2022-09-05 10:45 UTC, tiltom requested changes

2022-09-05 10:45 UTC, tiltom commented on packages/ui/package.json
> +    "classnames": "^2.3.1",
```suggestion
    "classnames": "2.3.1",
```

2022-09-05 10:45 UTC, tiltom commented on packages/ui/package.json
> +    "classnames": "^2.3.1",
Remove `^` in the **whole** file (not only your changes).

2022-09-05 10:45 UTC, tiltom commented on packages/ui/src/2_molecules/Dropdown/Dropdown.tsx
> +type IDropdownProps = {
```suggestion
type DropdownProps = {
```

2022-09-05 10:45 UTC, tiltom commented on packages/ui/src/2_molecules/Menu/components/MenuItem/MenuItem.tsx
> +  );
```suggestion
  const onClickHandler = useCallback(
    event => {
      if (disabled) {
        event.preventDefault();
        event.stopPropagation();
      } else {
        onClick?.(event);
      }
    },
    [onClick, disabled],
  );
```

2022-09-05 11:39 UTC, pietro-maximoff commented
@Rickk137 @tiltom I can't find any discussion about why we use CSS instead of SCSS in atom components or we planning to update them later?

2022-09-05 12:15 UTC, Rickk137 commented
> @Rickk137 @tiltom I can't find any discussion about why we use CSS instead of SCSS in atom components or we planning to update them later?

We have decide to stop using scss. @tiltom will update the code guideline

2022-09-05 12:43 UTC, tiltom commented
> 

We decided not to use `Sass` in one of our spikes regarding the new dapp. It's not something I think we need to have in guidelines but I updated the existing guidelines so we don't mention `scss` anymore.

2022-09-05 12:48 UTC, tiltom approved these changes

2022-09-05 15:52 UTC, pietro-maximoff approved these changes
looks good to me, there was an issue with css file naming, discussed it with Rick, and fixed with `git config core.ignorecase true`

2022-09-07 12:32 UTC, soulBit approved these changes

2022-09-07 15:29 UTC, merged