SOV-3225: Fix individual proposals opening
DistributedCollective/sovryn-dapp pull request #611
Opened 2023-09-29 10:14 UTC by tiltom

Resolves https://sovryn.atlassian.net/browse/SOV-3225

2023-09-29 10:39 UTC, creed-victor requested changes

2023-09-29 10:39 UTC, creed-victor commented on apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalViewButton/ProposalViewButton.tsx
> +      hrefExternal
```suggestion
```

2023-09-29 11:31 UTC, tiltom commented on apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalViewButton/ProposalViewButton.tsx
> +      hrefExternal
Good catch, fixed.

2023-09-29 12:21 UTC, creed-victor approved these changes

2023-10-03 12:34 UTC, tiltom commented
This functionality will be merged in https://github.com/DistributedCollective/sovryn-dapp/pull/620

2023-10-03 12:34 UTC, closed without merging