Sov 808 d 2 transaction step component
DistributedCollective/sovryn-dapp pull request #62
Opened 2022-11-02 10:33 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-808

2022-11-02 17:11 UTC, soulBit requested changes
Couple of changes to make from scope of this story.

There's also some functional/behavioural things not covered by this implementation (e.g. Tx id and Accordion visibility behaviour), but these can be picked up as part of SOV-823 (I'll add them to Jira)

2022-11-02 17:11 UTC, soulBit commented on apps/frontend/src/app/3_organisms/components/TransactionGas/TransactionGas.tsx
> +};
```suggestion
export const TransactionGas: FC<TransactionGasProps> = ({ limit, price }) => (
    <>
      <AmountInput
        label="Gas limit"
        className="mt-2 mb-4 max-w-64"
        min={0}
        value={limit}
      />
      <AmountInput
        label="Gas price"
        unit="Gwei"
        className="mb-4 max-w-64"
        min={0}
        value={price}
      />
    </>
  );
```

2022-11-02 17:11 UTC, soulBit commented on packages/ui/src/2_molecules/RadioButton/RadioButton.tsx
> +            data-layout-id={dataLayoutId}
```suggestion
            {...applyDataAttr(dataLayoutId)}
```
Switch this to use new utility function for applying layout id attribute, examples can be found in `SimpleTableRow` or other components

2022-11-02 17:11 UTC, soulBit commented on apps/frontend/src/app/3_organisms/components/TransactionGas/TransactionGas.tsx
> +import { AmountInput } from '@sovryn/ui';
Move `apps/frontend/src/app/3_organisms/components` folder to `apps/frontend/src/app/3_organisms/TransactionStep/components` and update any imports

2022-11-03 10:44 UTC, soulBit approved these changes

2022-11-03 10:50 UTC, pietro-maximoff approved these changes

2022-11-03 10:51 UTC, merged