Environment switching
DistributedCollective/sovryn-dapp pull request #65
Opened 2022-11-03 14:09 UTC by tiltom

Resolves https://sovryn.atlassian.net/browse/SOV-807

2022-11-03 14:57 UTC, creed-victor requested changes, later dismissed

2022-11-03 14:57 UTC, creed-victor commented on apps/frontend/craco.config.js
> +
```suggestion
const appMode = process.env.APP_MODE;
if (appMode) {
  dotenvCra.config({ env: appMode });
}
```

2022-11-07 12:07 UTC, soulBit approved these changes
Looks good if my comment from Jira is working as intended

2022-11-07 13:36 UTC, soulBit commented
Merging without re-review from Victor as his suggestion was implemented as described

2022-11-07 13:36 UTC, merged