SOV-892: Tab component styling updates
DistributedCollective/sovryn-dapp pull request #66
Opened 2022-11-03 16:11 UTC by soulBit

https://sovryn.atlassian.net/browse/SOV-892

2022-11-04 11:24 UTC, Rickk137 requested changes

2022-11-04 11:24 UTC, Rickk137 commented on packages/ui/src/2_molecules/Tabs/components/Tab/Tab.module.css
> +    @apply bg-gray-80 mx-1.5;
I think the first and last child should have 0 margin. we can use gap on parent or remove margin for last-first child here.

2022-11-04 11:40 UTC, soulBit commented on packages/ui/src/2_molecules/Tabs/components/Tab/Tab.module.css
> +    @apply bg-gray-80 mx-1.5;
nice catch, updated

2022-11-04 11:41 UTC, Rickk137 approved these changes

2022-11-04 12:41 UTC, pietro-maximoff approved these changes

2022-11-07 07:41 UTC, LunaSov approved these changes

2022-11-07 07:56 UTC, merged