SOV-3390: reimplement increasing debt without adding collateral
DistributedCollective/sovryn-dapp pull request #703
Opened 2023-11-29 10:02 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-3390

2023-11-29 15:10 UTC, tiltom requested changes

2023-11-29 15:10 UTC, tiltom commented on apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/AdjustLoanForm.tsx
> +  const [drawDown, setDrawDown] = useState(Decimal.ZERO);
It looks good but pls extract it to a custom hook that accepts `loan`, `isAddCollateralTab` and returns `drawdown` and `maxBorrow`.

2023-11-29 15:10 UTC, tiltom commented on apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/utils.ts
The filename should be `AdjustLoanForm.utils.ts`.

2023-11-29 16:22 UTC, Rickk137 requested changes

2023-11-29 16:22 UTC, Rickk137 commented on apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/utils.ts
> +  ).address;
you can use `Promise.all` for these async tasks

2023-11-29 16:22 UTC, Rickk137 commented on apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/utils.ts
> +  ).address;
you can use `Promise.all` for these async tasks

2023-11-30 10:23 UTC, soulBit approved these changes

2023-11-30 12:23 UTC, Rickk137 approved these changes

2023-12-05 10:03 UTC, merged