[VerticalTabsMobile] - add a component
DistributedCollective/sovryn-dapp pull request #71
Opened 2022-11-08 11:06 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-802

2022-11-08 12:58 UTC, creed-victor requested changes

2022-11-08 12:58 UTC, creed-victor commented on packages/ui/src/2_molecules/VerticalTabsMobile/VerticalTabsMobile.tsx
> +          </button>
Text assumes that component will be used for wallets only.

I think entire `button` should be removed from component and it should be added together with `renderContent`, so dev could make sure we can use custom back buttons or even prevent them from appearing.

2022-11-10 14:58 UTC, creed-victor requested changes

2022-11-10 14:58 UTC, creed-victor commented on packages/ui/src/2_molecules/VerticalTabsMobile/VerticalTabsMobile.module.css
> +  }
Remove it from here and apply classes inline - as it's only used in storybook it's ok on using tailwind classes directly there.

2022-11-10 14:58 UTC, creed-victor commented on packages/ui/src/2_molecules/VerticalTabsMobile/VerticalTabsMobile.stories.tsx
> +                  </button>
It's being repeated multiple times, make it a component and reuse it.

2022-11-10 16:42 UTC, creed-victor approved these changes

2022-11-11 10:19 UTC, soulBit approved these changes
Approving but we should replace the `<p>` and `<small>` tags in MobileVerticalTabItem component with `<Heading>`, once Victor has made adjustments to CSS overridesfor font color (or in SOV-1027, whichever comes first)

2022-11-15 11:01 UTC, LunaSov approved these changes

2022-11-15 11:06 UTC, merged