SOV-3411: Market Making Integration & Testing
DistributedCollective/sovryn-dapp pull request #712
Opened 2023-12-06 09:32 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-3411

2023-12-11 16:47 UTC, tiltom requested changes

2023-12-11 16:47 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/hooks/useGetMaxDeposit.ts
> +  const gasLimit = useMemo(
Use `composeGas` util function instead of manual calculation. You can see an example how to use it in `useMaxAssetBalance`.

2023-12-11 16:47 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.constants.tsx
> +      <div data-pool-key={`${pool.key}`}>
```suggestion
      <div data-pool-key={pool.key}>
```

2023-12-11 16:47 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
> +        data-pool-key={`${pool.key}`}
```suggestion
        data-pool-key={pool.key}
```

2023-12-11 16:47 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableAction/PoolsTableAction.tsx
> +                disabled={!account || isMynt}
Shouldn't the `MYNT` pool be visible only if I have some balance in it?

<img width="1194" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/20816c17-9ac4-44f9-9bec-920e6ee044dd">

2023-12-11 17:11 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableAction/PoolsTableAction.tsx
> +                disabled={!account || isMynt}
nope, we changed it to be visible all the time instead we will disable the deposit button and this button will be with a tooltip which explains why it's disabled

2023-12-12 09:46 UTC, tiltom approved these changes

2023-12-12 10:25 UTC, merged