Sov 152 d 2 wrong network switcher
DistributedCollective/sovryn-dapp pull request #72
Opened 2022-11-08 13:50 UTC by Rickk137

https://sovryn.atlassian.net/browse/SOV-152

2022-11-09 09:02 UTC, creed-victor requested changes

2022-11-09 09:02 UTC, creed-victor commented on apps/frontend/src/hooks/useWalletConnect.ts
> +  const switchNetwork = useCallback(async (chainId: string | number) => {
```suggestion
  const switchNetwork = useCallback(async (chainId: ChainId) => {
```

Note it's `ChainId` (which is union between ChainId and string) and not `ChainIds` (which is enum)

2022-11-09 09:02 UTC, creed-victor commented on apps/frontend/src/app/2_molecules/WrongNetworkSwitcher/WrongNetworkSwitcher.tsx
> +  }, [switchNetwork]);
Let's make some const outside of component (ex. `const requiredChain = ChainIds.RSK_TESTNET`) and use it for comparison there.
Then, we will be able to change that variable to some state when we will decide how it will be actually tracked.

2022-11-09 09:02 UTC, creed-victor commented on apps/frontend/src/locales/en/translations.json
> +        "description": "We detected that you are curently conected to the wrong network. please swich to the RSK network in your browser wallet"
```suggestion
        "description": "We detected that you are currently connected to the wrong network. Please switch your wallet to use {{network}} network."
```

2022-11-09 09:02 UTC, creed-victor commented on apps/frontend/src/app/2_molecules/WrongNetworkSwitcher/WrongNetworkSwitcher.tsx
> +        {t('wrongNetworkSwitcher.description')}
Pass required network chain id here (later we will give chain name, which will be included to #60 )

```suggestion
        {t('wrongNetworkSwitcher.description', { network: requiredChain })}
```

2022-11-10 09:51 UTC, pietro-maximoff requested changes

2022-11-10 09:51 UTC, pietro-maximoff commented on apps/frontend/src/app/2_molecules/WrongNetworkSwitcher/WrongNetworkSwitcher.tsx
> +  if (!isWrongChain) return null;
```suggestion
  if (!isWrongChain) {
    return null;
  }
```

2022-11-10 09:51 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/WalletIdentity/WalletIdentity.module.css
> +  width: 170px;
its better to use `w-44` instead of px;

2022-11-10 09:51 UTC, pietro-maximoff commented on packages/ui/src/2_molecules/WalletIdentity/WalletIdentity.module.css
> +}
```suggestion
}

```

2022-11-10 12:41 UTC, pietro-maximoff approved these changes

2022-11-10 15:07 UTC, creed-victor approved these changes

2022-11-11 14:41 UTC, LunaSov approved these changes

2022-11-11 16:08 UTC, merged