[Footer] - add a component
DistributedCollective/sovryn-dapp pull request #78
Opened 2022-11-11 07:57 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-793

2022-11-11 10:57 UTC, creed-victor requested changes

2022-11-11 10:57 UTC, creed-victor commented on packages/ui/src/2_molecules/Footer/Footer.module.css
> +    @apply ml-14 mt-0;
```suggestion
    @apply mt-0;
```

2022-11-11 10:57 UTC, creed-victor commented on packages/ui/src/2_molecules/Footer/Footer.stories.tsx
> +      <Link href="/zero" text="Zero" className="mr-2" />
```suggestion
      <Link href="/zero" text="Zero" className="mr-4" />
```

2022-11-11 10:57 UTC, creed-victor commented on packages/ui/src/2_molecules/Footer/Footer.module.css
> +  @apply flex-col;
```suggestion
  @apply flex-col gap-x-14;
```

2022-11-11 11:02 UTC, Rickk137 requested changes

2022-11-11 11:02 UTC, Rickk137 commented on packages/ui/src/2_molecules/Footer/Footer.stories.tsx
> +      <Link href="/zero" text="Zero" className="mr-2" />
<img width="696" alt="Screen Shot 2022-11-11 at 2 28 40 PM" src="https://user-images.githubusercontent.com/25097709/201326612-370cb285-216e-4526-bd65-dc83d6d9c714.png">

2022-11-11 11:02 UTC, Rickk137 commented on packages/ui/src/2_molecules/Footer/Footer.stories.tsx
> +          className="ml-2 border border-white/10 text-sov-white rounded-full w-6 h-6 p-0.5 flex justify-center items-center hover:bg-gray-80"
p-1.5

2022-11-11 11:38 UTC, Rickk137 approved these changes

2022-11-14 17:05 UTC, creed-victor approved these changes

2022-11-15 12:02 UTC, LunaSov approved these changes

2022-11-15 12:04 UTC, merged