SOV-3777: boltz v2 api
DistributedCollective/sovryn-dapp pull request #801
Opened 2024-03-07 13:04 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-3777

2024-03-11 10:05 UTC, rick23p requested changes

2024-03-11 10:05 UTC, rick23p commented on apps/frontend/src/app/3_organisms/FastBtcDialog/utils/boltz/boltz.client.ts
> +const client = Axios.create({
boltzClient? and doesn't need to be exported

2024-03-11 10:05 UTC, rick23p commented on apps/frontend/src/app/3_organisms/FastBtcDialog/utils/boltz/boltz.types.ts
> +export enum StatusEnum {
I think this can be better named

2024-03-12 08:34 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/FastBtcDialog/utils/boltz/boltz.client.ts
> +const client = Axios.create({
It's being wrapped by functions in this file and does not used for outside it, so i don't think we need need it exported

2024-03-12 08:35 UTC, creed-victor commented on apps/frontend/src/app/3_organisms/FastBtcDialog/utils/boltz/boltz.types.ts
> +export enum StatusEnum {
Open to suggestions, just that StatusType are already used in the fastbtc flows

2024-03-12 11:26 UTC, rick23p commented on apps/frontend/src/app/3_organisms/FastBtcDialog/utils/boltz/boltz.types.ts
> +export enum StatusEnum {
Maybe `BoltzTxStatus`

2024-03-12 11:26 UTC, rick23p approved these changes

2024-03-12 13:23 UTC, merged