SOV-3966: refactor token list
DistributedCollective/sovryn-dapp pull request #808
Opened 2024-03-14 06:44 UTC by creed-victor

2024-03-19 16:41 UTC, tiltom requested changes

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/TreasuryStep/components/Parameter/Parameter.tsx
> +        .filter(token => token.symbol !== 'WBTC')
```suggestion
        .filter(token => token.symbol !== COMMON_SYMBOLS.WBTC)
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/BorrowPage/BorrowPage.utils.tsx
> +    return 'BPRO';
Maybe add `BPRO` to `COMMON_SYMBOLS`.

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/BorrowPage/BorrowPage.utils.tsx
> +    return 'WBTC';
```suggestion
    return COMMON_SYMBOLS.WBTC;
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/BorrowPage/hooks/useGetBorrowMaintenance.ts
> +      case 'DOC':
```suggestion
      case COMMON_SYMBOLS.DOC:
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.constants.ts
> +  'DOC',
```suggestion
  COMMON_SYMBOLS_DOC,
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.constants.ts
> +export const BASSETS = [COMMON_SYMBOLS.ZUSD, 'DOC'];
```suggestion
export const BASSETS = [COMMON_SYMBOLS.ZUSD, COMMON_SYMBOLS.DOC];
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
> +    if (hasMyntBalance && fromToken === 'MYNT') {
Add `MYNT` as a local const at least.

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.constants.ts
> +    'XUSD',
```suggestion
    COMMON_SYMBOLS_XUSD,
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.constants.ts
> +    'DOC',
```suggestion
    COMMON_SYMBOLS.DOC,
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.constants.ts
> +    'DOC',
```suggestion
    COMMON_SYMBOLS.DOC,
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/hooks/useGetPoolBalanceAndRewards.ts
> +  const poolContract = useGetTokenContract('WBTC', RSK_CHAIN_ID);
```suggestion
  const poolContract = useGetTokenContract(COMMON_SYMBOLS.WBTC, RSK_CHAIN_ID);
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/hooks/useGetPoolsBalance.ts
> +        getAssetData('WBTC', RSK_CHAIN_ID),
```suggestion
        getAssetData(COMMON_SYMBOLS.WBTC, RSK_CHAIN_ID),
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useCheckPoolMaintenance.ts
> +      case 'SOV':
```suggestion
      case COMMON_SYMBOLS.SOV:
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useCheckPoolMaintenance.ts
> +      case 'DLLR':
```suggestion
      case COMMON_SYMBOLS.DLLR:
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetPoolLiquidity.ts
> +          fetchBalance(contractTokenB, 'WBTC'),
```suggestion
          fetchBalance(contractTokenB, COMMON_SYMBOLS..WBTC),
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetUserInfo.ts
> +  const contractTokenB = useGetTokenContract('WBTC', RSK_CHAIN_ID);
```suggestion
  const contractTokenB = useGetTokenContract(COMMON_SYMBOLS..WBTC, RSK_CHAIN_ID);
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useHandleMarketMaking.ts
> +      const tokenBContractPromise = getAssetContract('WBTC', RSK_CHAIN_ID).then(
```suggestion
      const tokenBContractPromise = getAssetContract(COMMON_SYMBOLS..WBTC, RSK_CHAIN_ID).then(
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
> +        earnedFee.token.toUpperCase() === 'WBTC',
```suggestion
        earnedFee.token.toUpperCase() === COMMON_SYMBOLS.BTC ||
        earnedFee.token.toUpperCase() === COMMON_SYMBOLS..WBTC,
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
> +        earnedFee.token.toUpperCase() !== 'WBTC',
```suggestion
        earnedFee.token.toUpperCase() !== COMMON_SYMBOLS.BTC &&
        earnedFee.token.toUpperCase() !== COMMON_SYMBOLS.WBTC,
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
> +      token: 'BTC',
```suggestion
      token: COMMON_SYMBOLS.BTC,
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/utils/asset.ts
> +export const normalizeAsset = (asset: string, chainId: ChainId) =>
I am not sure about the name, I'd probably name it `findAsset` or `getAssetDetails` because that's basically what you do there.

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/utils/asset.ts
> +export const normalizeNativeAsset = (chainId: ChainId) =>
Again, I'd probably name it `findNativeAsset` or `getNativeAssetDetails`.

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/utils/asset.ts
> +    return 'WBTC';
```suggestion
    return COMMON_SYMBOLS.WBTC;
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/utils/asset.ts
> +export const COMMON_SYMBOLS = {
I'd add more tokens here, at least `Bitpro`.

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/utils/asset.ts
> +    asset === 'WBTC' &&
```suggestion
    asset === COMMON_SYMBOLS.WBTC &&
```

2024-03-19 16:41 UTC, tiltom commented on apps/frontend/src/utils/helpers.ts
> +  asset.toLowerCase() === 'rbtc' ||
Add `RBTC` and `WRBTC` to `COMMON_SYMBOLS` and use it here.

2024-03-20 09:06 UTC, creed-victor commented on apps/frontend/src/utils/helpers.ts
> +  asset.toLowerCase() === 'rbtc' ||
RBTC and WRBTC are only used once in the entire dapp, so i prefer leaving them out of common symbols

2024-03-20 13:41 UTC, tiltom approved these changes

2024-03-20 14:29 UTC, merged