SOV-3930: Staking page updates
DistributedCollective/sovryn-dapp pull request #816
Opened 2024-03-21 12:35 UTC by rick23p

https://sovryn.atlassian.net/browse/SOV-3930

2024-04-03 12:19 UTC, soulBit requested changes

2024-04-03 12:19 UTC, soulBit commented on apps/frontend/src/app/5_pages/StakePage/components/StakingStatistics/StakingStatistics.tsx
> +  const chainId = useCurrentChain();
Can't leave a comment there but line 34 needs to be updated to use this variable, currently it's pulling total staked SOV from RSK

2024-04-03 12:33 UTC, creed-victor commented on apps/frontend/src/app/5_pages/StakePage/components/StakingStatistics/StakingStatistics.tsx
> +        {chainId !== BOB_CHAIN_ID && (
```suggestion
        {!isBobChain(chainId) && (
```

2024-04-04 12:12 UTC, soulBit approved these changes

2024-04-09 08:38 UTC, merged