[LanguageSelector] - add component
DistributedCollective/sovryn-dapp pull request #82
Opened 2022-11-12 08:26 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-788

2022-11-15 13:38 UTC, Rickk137 commented
@pietro-maximoff Is it possible to close dropdown once language is selected?

2022-11-15 13:44 UTC, Rickk137 requested changes

2022-11-15 13:44 UTC, Rickk137 commented on apps/frontend/src/app/2_molecules/LanguageSelector/LanguageSelector.tsx
> +      {...applyDataAttr(dataLayoutId)}
size={DropdownSize.small}

2022-11-16 00:23 UTC, soulBit requested changes

2022-11-16 00:23 UTC, soulBit commented on apps/frontend/src/app/2_molecules/LanguageSelector/LanguageSelector.tsx
> +import { applyDataAttr } from '@sovryn/ui/src/utils';
```suggestion
import {
  Menu,
  MenuItem,
  Dropdown,
  DropdownSize,
  applyDataAttr,
} from '@sovryn/ui';
```

2022-11-16 00:23 UTC, soulBit commented on yarn.lock
> +"@types/reactjs-localstorage@^1.0.0":
```suggestion
"@types/reactjs-localstorage@1.0.0":
```
Run `yarn` again and lockfile should be updated with this new dependency version

2022-11-16 08:47 UTC, soulBit approved these changes

2022-11-16 08:54 UTC, Rickk137 approved these changes

2022-11-16 09:03 UTC, merged