Rune bridge UI
DistributedCollective/sovryn-dapp pull request #838
Opened 2024-04-15 06:42 UTC by koirikivi

The flow works, but still has some things that should be improved. Please talk to me when taking under review.

2024-04-16 15:05 UTC, tiltom requested changes

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/RuneBridgeDialog.tsx
> +const ACTIVE_CLASSNAME = 'border-t-primary-30';
Move to `./constants.ts`.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/RuneBridgeDialog.tsx
> +  shouldHideSend?: boolean;
`shouldHideSend` is not used, do you need it? We have it in FastBTC flow only because we don't want our users to use us as a TBTC faucet.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/api/index.tsx
> +export const runeBridgeApiClient = new RuneBridgeClient(baseUrl);
The file extension should be extension `.ts` not `.tsx` since you don't render anything.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/GoBackButton.tsx
> +export const GoBackButton: React.FC<GoBackButtonProps> = ({ onClick }) => (
It's the exact same component as in the Fast BTC flow so extract it to `/app/1_atoms` as a separate component and use that instead.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/MobileCloseButton.tsx
> +export const MobileCloseButton: React.FC<MobileCloseButtonProps> = ({
The same thing as `GoBackButton`, create a new component in atoms instead and use it here and in Fast BTC flow.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RSKToRune/RSKToRune.tsx
> +interface RSKToRuneProps {
```suggestion
type RskToRuneProps {
```
We use `type` instead of `interface` if possible.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RSKToRune/RSKToRune.tsx
> +export const RSKToRune: React.FC<RSKToRuneProps> = ({ onClose }) => {
I would use the same naming convention as in the FastBTC dialog (so this would be `SendFlow` and `RuneToRSK` would be `ReceiveFlow`).

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RSKToRune/components/AddressForm.tsx
> +  const { address, set, addressValidationState } = useContext(SendFlowContext);
Create a const in `SendFlowContext` named `useSendFlowContext` and use it instead. Do it for all the contexts in the Runes bridge.

You can find an example in `TransactionContext.tsx`.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RSKToRune/components/AmountForm.tsx
> +    });
```suggestion
    const tokenBalance = tokenBalances.find(
      token =>
        token.tokenContractAddress === selectedToken.tokenContractAddress,
    );
```

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RSKToRune/components/AmountForm.tsx
> +              onChange={e => onSelectToken(e)}
```suggestion
              onChange={onSelectToken}
```

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RSKToRune/components/AmountForm.tsx
> +            serviceFee={`${WITHDRAW_FEE_RUNE_PERCENTAGE}% + ${WITHDRAW_FEE_BASE_CURRENCY_BTC} BTC`}
```suggestion
            serviceFee={`${WITHDRAW_FEE_RUNE_PERCENTAGE}% + ${WITHDRAW_FEE_BASE_CURRENCY_BTC} ${BITCOIN}`}
```

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RSKToRune/components/ReviewScreen.tsx
> +}
```suggestion
type FeesPaid {
  rune: number;
  baseCurrency: number;
}

type ReviewScreenProps {
  from: string;
  to: string;
  amount: string;
  feesPaid: FeesPaid;
  receiveAmount: number;
  onConfirm: () => void;
}
```

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RuneExplorerLink.tsx
> +  process.env.REACT_APP_NETWORK === Environments.Testnet
```suggestion
  currentNetwork === Environments.Testnet
```

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RuneExplorerLink.tsx
> +};
```suggestion
export const RuneExplorerLink = ({ rune }: RuneExplorerLinkProps) => (
  <a
    href={`${EXPLORER_BASE_URL}/rune/${rune}`}
    target="_blank"
    rel="noopener noreferrer"
  >
    {rune}
  </a>
);
```

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/index.tsx
> +export * from './RSKToRune/RSKToRune';
You don't need this file, delete it pls.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/contextproviders/ContractContextProvider.tsx
> +export const ContractContextProvider: React.FC<
I'd name the context (and file) `RuneContext`.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/contextproviders/ContractContextProvider.tsx
> +    const refreshTokenBalancesInterval = setInterval(
Use our custom hook `useInterval`. Also, I don't think you need to refresh token balances every 5 seconds since the block time on RSK is ~30 seconds. I know it can be different on other chains (e.g. BoB) but I'd say set it to at least 10 seconds.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/contextproviders/ContractContextProvider.tsx
> +    const refreshTokenBalancesTimeout = setTimeout(requestTokenBalances, 500);
Why do you need timeout?

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/contextproviders/SendContextProvider.tsx
> +export const SendFlowContextProvider: React.FC<
Rename the file to `SendFlowContext`.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/contexts/contract.ts
> +export const Contract = React.createContext(defaultValue);
I would expect this in the `RuneContext` directly along with `defaultValue` and some other stuff but let's leave it as is for now.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/hooks/useContractService.tsx
> +  return {
I don't think you need to return the values from `Contract` context, you can access them directly if needed and you should only return `requestDepositAddress`.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/hooks/useReceiveFlowService.ts
> +export const useReceiveFlowService = () => {
I think that this whole file can be deleted and you can use `ReceiveFlowContext` and `requestDepositAddress` directly when needed.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/hooks/useSendFlowService.ts
> +export const useSendFlowService = () => {
This file should be deleted and you can use `SendFlowContext` directly.

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/types/global.ts
> +export enum ExplorerNetworkURI {
We have it defined in `infrastructure.ts` already (`RSK_EXPLORER`).

2024-04-16 15:05 UTC, tiltom commented on apps/frontend/src/utils/helpers.ts
> +export const currentBTCNetwork: Network =
```suggestion
export const currentBtcNetwork: Network =
```

2024-04-17 10:12 UTC, koirikivi commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/contextproviders/ContractContextProvider.tsx
> +    const refreshTokenBalancesTimeout = setTimeout(requestTokenBalances, 500);
Yeah, don't really. useInterval with { immediate: true } is better

2024-04-17 10:12 UTC, koirikivi commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/contextproviders/ContractContextProvider.tsx
> +    const refreshTokenBalancesInterval = setInterval(
Good catch!

2024-04-17 14:56 UTC, tiltom requested changes

2024-04-17 14:56 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/SendFlow/components/AddressForm.tsx
> +  const { address, set, addressValidationState } = useContext(SendFlowContext);
```suggestion
  const { address, set, addressValidationState } = useSendFlowContext();
```

2024-04-17 14:56 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/RuneExplorerLink.tsx
> +export const RuneExplorerLink = ({ rune }: RuneExplorerLinkProps) => (
```suggestion
export const RuneExplorerLink: FC<RuneExplorerLinkProps> = ({ rune }) => (
```

2024-04-17 14:56 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/contexts/rune.ts
> +  set: () => {},
```suggestion
  set: noop,
```

2024-04-17 14:56 UTC, tiltom commented on apps/frontend/src/app/3_organisms/RuneBridgeDialog/contexts/sendflow.ts
> +  set: () => {},
```suggestion
  set: noop,
```

2024-04-18 06:35 UTC, tiltom approved these changes

2024-04-18 14:56 UTC, tiltom approved these changes

2024-04-19 17:42 UTC, merged