[Footer] - add a footer to the dapp2
DistributedCollective/sovryn-dapp pull request #85
Opened 2022-11-15 15:02 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-827

2022-11-16 09:27 UTC, soulBit requested changes

2022-11-16 09:27 UTC, soulBit commented on apps/frontend/src/app/3_organisms/Footer/Footer.tsx
> +          dataAttribute="logo"
Pass in "Powered by Bitcoin" text and small Sovryn logo (without "Sovryn" text) here, from Figma design

2022-11-16 09:27 UTC, soulBit commented on apps/frontend/src/app/5_pages/App/App.tsx
> +    <div className="relative">
This breaks the footer sticking to bottom of screen, and positioning of Osano cookie consent button

![image](https://user-images.githubusercontent.com/765825/202141568-b7ec0c8f-d549-49b1-bf88-b552b0dbee1b.png)

2022-11-16 09:27 UTC, soulBit commented on apps/frontend/src/app/3_organisms/Footer/Footer.tsx
> +      id: 'alfa',
```suggestion
      id: 'dapp-alpha',
```

2022-11-16 09:27 UTC, soulBit commented on apps/frontend/src/app/3_organisms/Footer/Footer.tsx
> +      href: 'https://wiki.sovryn.app/en/getting-started',
Move this link and the others in this file to `apps/frontend/src/utils/constants.ts`

2022-11-16 14:14 UTC, creed-victor requested changes

2022-11-16 14:14 UTC, creed-victor commented on apps/frontend/src/app/2_molecules/SovrynLogo/SovrynLogo.tsx
> +      <div className={classNames(styles.logo)}>
```suggestion
      <div className={styles.logo}>
```

2022-11-16 14:19 UTC, soulBit approved these changes

2022-11-16 14:23 UTC, creed-victor approved these changes

2022-11-17 10:43 UTC, LunaSov approved these changes

2022-11-17 10:58 UTC, merged