SOV-4072: dollar value issue
DistributedCollective/sovryn-dapp pull request #867
Opened 2024-04-24 11:14 UTC by rick23p

https://sovryn.atlassian.net/browse/SOV-4072
https://sovryn.atlassian.net/browse/SOV-4065

2024-04-24 11:24 UTC, creed-victor requested changes

2024-04-24 11:24 UTC, creed-victor commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/components/AmbientPoolPositions/components/AmbientPositionPrices/AmbientPositionPrices.tsx
> +  if (position.bidTick === MIN_TICK && position.askTick === MAX_TICK) {
```suggestion
  if (position.positionType === 'ambient' || (position.bidTick === MIN_TICK && position.askTick === MAX_TICK)) {
```

2024-04-24 11:24 UTC, creed-victor commented on apps/frontend/src/hooks/useDollarValue.ts
>      `dollarValue/${asset}`,
```suggestion
    `dollarValue/${chainId || chain}/${asset}`,
```

2024-04-24 11:24 UTC, creed-victor commented on apps/frontend/src/hooks/useDollarValue.ts
>    const { price: btcPrice } = useGetRBTCPrice();
Remove it altogether
```suggestion
```

2024-04-24 11:24 UTC, creed-victor commented on apps/frontend/src/hooks/useDollarValue.ts
> +        )
```suggestion
        .mul(usdPrice)
```

2024-04-25 09:20 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/components/AmbientPoolPositions/components/AmbientPositionPrices/AmbientPositionPrices.tsx
> +      position.positionType === 'ambient' ||
```suggestion
      position.positionType === PoolPositionType.ambient ||
```

2024-04-25 12:20 UTC, creed-victor approved these changes

2024-04-25 12:20 UTC, merged