SOV-4139: BoB Spice leaderboard
DistributedCollective/sovryn-dapp pull request #904
Opened 2024-05-11 06:57 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-4139

2024-05-13 08:14 UTC, creed-victor requested changes

2024-05-13 08:14 UTC, creed-victor commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/BalanceRenderer/BalanceRenderer.tsx
> +  );
put it under useMemo

2024-05-13 13:57 UTC, tiltom requested changes

2024-05-13 13:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.constants.tsx
> +    title: isUserPosition
This doesn't make sense.
<img width="1586" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/b4856e70-39a6-4427-bcaf-848df6a2cd5a">

Take a look at how it's handled in the POWA page and do it similarly (consult with fineline or Hyde if not sure): https://github.com/DistributedCollective/sovryn-dapp/blob/98b527d4add1eb75e1f9db7da6dc534c86e70985/apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.constants.tsx#L22

2024-05-13 13:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.constants.tsx
> +    id: 'balance',
Consult with fineline and Hyde but I don't like the fact that `Balance` is shown only for the connected wallet and it's empty for all the rows.

2024-05-13 13:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/hooks/useGetPoints.ts
> +  const usersPointsData: UserPoints[] = usersPointsList;
```suggestion
  const data: UserPoints[] = usersPointsList;
```
Move it above the hook.

2024-05-13 13:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/hooks/useGetPoints.ts
> +  const endIndex = Math.min(startIndex + pageSize, usersPointsList.length);
```suggestion
  const startIndex = page * pageSize;
  const endIndex = Math.min(startIndex + pageSize, usersPointsList.length);
```
Use `useMemo`.

2024-05-13 13:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/hooks/useGetPoints.ts
> +  const userPoints: User[] = useMemo(() => {
```suggestion
  const connectedWalletPoints: User[] = useMemo(() => {
```

2024-05-13 13:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/hooks/useGetPoints.ts
> +  const usersPoints: User[] = useMemo(
```suggestion
  const points: User[] = useMemo(
```

2024-05-13 13:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/hooks/useGetPoints.ts
> +      ];
```suggestion
      const {wallet, points} = sortedUsers[userIndex];
      return [
        {
          id: userIndex + 1,
          wallet,
          spice: points,
          extraSpice: points * EXTRA_SPICE_POINTS_MULTIPLIER,
          runes: points * RUNES_POINTS_MULTIPLIER,
        },
      ];
```

2024-05-13 13:57 UTC, tiltom commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/hooks/useGetPoints.ts
> +      })),
```suggestion
      sortedUsers.slice(startIndex, endIndex).map(({wallet, points}, index) => ({
        id: startIndex + index + 1,
        wallet,
        spice: points,
        extraSpice: points * EXTRA_SPICE_POINTS_MULTIPLIER,
        runes: points * RUNES_POINTS_MULTIPLIER,
      })),
```

2024-05-14 13:55 UTC, tiltom approved these changes

2024-05-14 13:55 UTC, tiltom commented on apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/ConnectWalletMessage/ConnectWalletMessage.tsx
> +export const ConnectWalletMessage = () => {
Can you just reuse the existing component and move it to `app/1_atoms` or `app/2_molecules`?

2024-05-15 13:55 UTC, soulBit approved these changes

2024-05-15 13:55 UTC, merged