chore: fixed dropdown issue when resizing the screen
DistributedCollective/sovryn-dapp pull request #91
Opened 2022-11-17 09:17 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-788

2022-11-17 10:57 UTC, soulBit requested changes

2022-11-17 10:57 UTC, soulBit commented on apps/frontend/src/app/2_molecules/LanguageSelector/LanguageSelector.tsx
> +      <Menu className={styles.menu}>
![image](https://user-images.githubusercontent.com/765825/202428149-f253383e-440c-402b-9037-ce50bd215c1e.png)

Menu positioning is a bit off in fullscreen (1080px width) when page is first loaded and dropdown clicked - if I resize window to be smaller, and then make it fullscreen again, positioning fixes itself

2022-11-17 14:34 UTC, pietro-maximoff commented on apps/frontend/src/app/2_molecules/LanguageSelector/LanguageSelector.tsx
> +      <Menu className={styles.menu}>
fixed + fixed in storybook as well

2022-11-21 10:45 UTC, soulBit approved these changes

2022-11-21 10:57 UTC, Rickk137 commented
If you open dropdown and scroll down this issue occurs:

<img width="245" alt="Screen Shot 2022-11-21 at 2 27 25 PM" src="https://user-images.githubusercontent.com/25097709/203033477-28ab1ccc-e803-4225-a345-3f11fc782b20.png">
<img width="245" alt="Screen Shot 2022-11-21 at 2 27 31 PM" src="https://user-images.githubusercontent.com/25097709/203033508-0d96a59c-7235-4445-8b0d-fa39453d3a38.png">

2022-11-21 16:43 UTC, Rickk137 approved these changes

2022-11-22 10:48 UTC, LunaSov approved these changes

2022-11-22 10:52 UTC, merged