SOV-4162: Unbalanced single sided ranged liquidity deposits
DistributedCollective/sovryn-dapp pull request #924
Opened 2024-05-27 16:26 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-4162

2024-05-28 13:59 UTC, tiltom requested changes

2024-05-28 13:59 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/BobDepositModal/components/PriceRange/components/AmountForm/AmountForm.tsx
> +      setSecondAssetValue(secondAssetQuantity);
```suggestion
if (secondAssetQuantity !== null) {
        setSecondAssetValue(secondAssetQuantity);
      }
```

2024-05-28 13:59 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/BobDepositModal/components/PriceRange/components/AmountForm/AmountForm.tsx
> +      setFirstAssetValue(firstAssetQuantity);
```suggestion
if (firstAssetQuantity !== null) {
        setFirstAssetValue(firstAssetQuantity);
      }
```

2024-05-28 13:59 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/BobDepositModal/components/PriceRange/components/AmountForm/AmountForm.tsx
> +        {isFirstAssetOutOfRange && !isBalancedRange && (
If an input is disabled, you should also reset the value because now it seems I will deposit 40 SOV as well for instance.
<img width="477" alt="image" src="https://github.com/DistributedCollective/sovryn-dapp/assets/14878713/b4482d1c-d0cd-408f-8b20-de40b918cd51">

2024-05-28 13:59 UTC, tiltom commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/BobDepositModal/components/PriceRange/components/UnbalancedRange/components/Input/Input.tsx
> +        precision={6}
What is the reason for this change?

2024-05-28 14:20 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/MarketMakingPage/components/BobDepositModal/components/PriceRange/components/UnbalancedRange/components/Input/Input.tsx
> +        precision={6}
@tiltom the reason is to fix the UI
<img width="461" alt="Screenshot at May 27 12-34-06" src="https://github.com/DistributedCollective/sovryn-dapp/assets/74987028/f6cd7096-d9b1-42eb-9ac8-99722371aac4">

2024-05-29 11:30 UTC, tiltom approved these changes

2024-06-18 12:41 UTC, pietro-maximoff commented
moved changes into this [PR](https://github.com/DistributedCollective/sovryn-dapp/pull/932)

2024-06-18 12:41 UTC, closed without merging