SOV-1013: zero credit line form
DistributedCollective/sovryn-dapp pull request #93
Opened 2022-11-17 14:11 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-1013

2022-12-08 13:58 UTC, Rickk137 requested changes

2022-12-08 13:58 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +            ]}
use useMemo

2022-12-08 13:58 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +            ]}
useMemo

2022-12-08 13:58 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +                )}
useCallback

2022-12-08 13:58 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/ZeroLocForm/SimpleTableRow.tsx
> +export const Row: FC<RowProps> = ({ label, tooltip, ...props }) => (
the component name and file name doesn't match

2022-12-08 13:58 UTC, Rickk137 commented on apps/frontend/src/app/4_templates/MainLayout/MainLayout.tsx
> +  <>
unnecessary <></>

2022-12-08 13:58 UTC, Rickk137 commented on apps/frontend/src/app/3_organisms/ZeroLocForm/types.ts
> +}
export enum AmountType {
  Add = 'Add',
  Remove = 'Remove',
}

2022-12-08 13:58 UTC, Rickk137 commented on apps/frontend/src/app/5_pages/ErrorPage/ErrorPage.tsx
> +  console.error(error);
is this expected here?

2022-12-08 13:58 UTC, Rickk137 commented on apps/frontend/src/app/5_pages/ErrorPage/ErrorPage.tsx
> +      <p>
use translation

2022-12-09 15:04 UTC, tiltom requested changes
Make sure that every value is properly localized because we're inconsistent right now. I don't think we should use `commify` package at all.
<img width="446" alt="Screenshot 2022-12-09 at 15 34 34" src="https://user-images.githubusercontent.com/14878713/206731649-2da58c14-2453-4d2c-b16d-54c60765cce7.png">

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +  const tokens = useMemo(
Don't hardcode `tokens` but use `SupportedTokens` enum and move `tokens` outside the component (either above it or to `types.ts`).

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +  const maxCreditAmount = 100;
Move these variables outside the component for now.

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +          <AmountInput
I think you should set `maxAmount` property that equals to `maxCreditAmount`, otherwise you will be able to enter more than is possible.

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +          <Select
This select is not working, there is always `DLLR`.

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +        <AmountInput
The same as with `creditAmount` input, you should set `maxAmount={maxCollateralAmount}`.

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +                renderer={value => <>{commify(value)} USD</>}
I don't think we need `commify`, we need to localize the same way as we do in `AmountInput`.

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/CustomLabel.tsx
> +export const Label: FC<CustomLabelProps> = memo(
Why do you use `memo`? Did you have some performance problems with the component?

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/CustomLabel.tsx
> +          (max {maxAmount.toFixed(4)} {symbol})
`maxAmount` should be localized (the same way as in `AmountInput`).

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/4_templates/MainLayout/MainLayout.tsx
> +export const MainLayout: FC = () => (
I don't see this component being used anywhere.

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/5_pages/PrivacyPolicy/PrivacyPolicy.tsx
> +  <>
Unnecessary `Fragment`.

2022-12-09 15:04 UTC, tiltom commented on apps/frontend/src/app/5_pages/TermsOfUse/TermsOfUse.tsx
> +  <>
Unnecessary `Fragment`.

2022-12-09 15:04 UTC, tiltom commented on packages/ui/src/1_atoms/DynamicValue/DynamicValue.tsx
> +export const DynamicValue = memo(
Did you have some performance problems with the component?

2022-12-09 16:08 UTC, Rickk137 commented
The dropdown select doesn't work is that expected?
<img width="342" alt="Screen Shot 2022-12-09 at 7 37 58 PM" src="https://user-images.githubusercontent.com/25097709/206743788-f1229c4f-4363-4433-a496-7ce7c9fd555c.png">

2022-12-09 16:09 UTC, Rickk137 commented
Token icon is missing
<img width="235" alt="Screen Shot 2022-12-09 at 7 39 06 PM" src="https://user-images.githubusercontent.com/25097709/206743995-5a960a14-67e7-4b55-8480-0859e6d7be91.png">
<img width="235" alt="Screen Shot 2022-12-09 at 7 39 11 PM" src="https://user-images.githubusercontent.com/25097709/206744012-3738d2c9-1fff-4268-9271-4e5ee8867989.png">

2022-12-11 17:21 UTC, creed-victor commented
> Make sure that every value is properly localized because we're inconsistent right now. I don't think we should use `commify` package at all.

What's expected result here? For example correct formatting of `1000` for `en-GB` locale with 2 decimal points should be `1,000.00`. To my opinion it looks like that amount input formatting is not quite right


> The dropdown select doesn't work is that expected?

Nope, issue with select using portals. Fixed by disabling focus on dialog.


> Token icon is missing

It's for token selector component, out of scope for this story.

2022-12-12 10:11 UTC, Rickk137 approved these changes

2022-12-12 10:37 UTC, tiltom requested changes
1. I think you should uppercase a unit in Borrow/Repay amount as well.
2. In case there is no new debt/collateral, it should say "N/A" according to the design.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/14878713/207024441-fa39b2b8-0a9d-4c78-873a-f80333de9d5f.png">

2022-12-12 10:37 UTC, tiltom commented on apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
> +  const collateraltabs = useMemo(
```suggestion
  const collateralTabs = useMemo(
```

2022-12-12 10:37 UTC, tiltom commented on apps/frontend/src/utils/math.ts
> +    minimumFractionDigits: precision,
```suggestion

```

2022-12-12 10:37 UTC, tiltom commented on packages/ui/src/1_atoms/DynamicValue/DynamicValue.tsx
> +};
```suggestion
export const DynamicValue = <T extends number>({
  initialValue,
  value,
  loading,
  renderer,
}: DynamicValueProps<T>) => (
  <div
    className={classNames('transition-colors duration-300', {
      'text-gray-30': initialValue === value,
      'text-primary-10': initialValue !== value,
      'text-gray-10': loading,
    })}
  >
    {loading ? (
      <Icon icon={IconNames.PENDING} size={13} />
    ) : renderer ? (
      <>{renderer(value)}</>
    ) : (
      <>{value}</>
    )}
  </div>
);
```

2022-12-12 13:26 UTC, tiltom requested changes

2022-12-12 13:26 UTC, tiltom commented on apps/frontend/src/utils/math.ts
> +): string => Number(Number(fromWei(value, unitName))).toFixed(decimals);
```suggestion
): string => Number(fromWei(value, unitName)).toFixed(decimals);
```

2022-12-12 15:10 UTC, merged