SOV-3945: prevent claiming of "dead vestings"
DistributedCollective/sovryn-dapp pull request #964
Opened 2024-07-23 11:32 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-3945

2024-07-26 07:10 UTC, pietro-maximoff requested changes

2024-07-26 07:10 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/WithdrawButton/WithdrawButton.tsx
> +    () => !result || result === 0 || (count >= 43 && item.type === 'Rewards'),
use constant for `43` and for `'Rewards'` use `VestingContractType.Rewards`

2024-07-26 07:10 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/UnclaimedVestingAlert/UnclaimedVestingAlert.tsx
> +  if (count > 32 && count < 43) {
move numbers to constants file

2024-07-26 07:10 UTC, pietro-maximoff commented on apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/UnlockSchedule/UnlockSchedule.tsx
> +    });
```suggestion
    update(state => (state.item = item));
```

2024-07-26 09:19 UTC, pietro-maximoff approved these changes

2024-08-01 11:10 UTC, soulBit approved these changes

2024-08-01 11:10 UTC, merged