[Notification] - add component
DistributedCollective/sovryn-dapp pull request #97
Opened 2022-11-22 14:50 UTC by pietro-maximoff

https://sovryn.atlassian.net/browse/SOV-1031

2022-11-23 14:09 UTC, soulBit approved these changes
Made two small adjustments - unused `className` prop in `WrongNetworkSwitcher`, and based on our discussion earlier I also removed absolute positioning from UI library component itself.

2022-11-24 09:51 UTC, Rickk137 requested changes

2022-11-24 09:51 UTC, Rickk137 commented on apps/frontend/src/app/2_molecules/WrongNetworkSwitcher/WrongNetworkSwitcher.tsx
> +        </>
`<Paragraph>
            {t('wrongNetworkSwitcher.description', {
              network: defaultChain?.label,
            })}
          </Paragraph>`

2022-11-24 10:00 UTC, Rickk137 requested changes

2022-11-24 10:00 UTC, Rickk137 commented on packages/ui/src/2_molecules/Notification/Notification.tsx
> +      )}
this can be removed and passed in content

2022-11-24 10:00 UTC, Rickk137 commented on packages/ui/src/2_molecules/Notification/Notification.tsx
> +  }, [onClick, onClose]);
this can be removed with the ``buttonLabel`` removal

2022-11-24 13:17 UTC, Rickk137 approved these changes

2022-11-25 08:33 UTC, LunaSov approved these changes

2022-11-25 08:41 UTC, merged