SOV-1007: add checkbox component
DistributedCollective/sovryn-dapp pull request #98
Opened 2022-11-23 10:56 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-1007

2022-11-23 14:42 UTC, soulBit approved these changes
Changed `dataLayoutId` prop to `dataAttribute`, and approved

2022-11-24 09:43 UTC, Rickk137 requested changes

2022-11-24 09:43 UTC, Rickk137 commented on packages/ui/src/1_atoms/Checkbox/Checkbox.test.tsx
> +    expect(container.querySelector('input[type=checkbox')).toBeInTheDocument();
input[type=checkbox]

2022-11-24 09:43 UTC, Rickk137 commented on packages/ui/src/1_atoms/Checkbox/Checkbox.test.tsx
> +      'input[type=checkbox',
input[type=checkbox]

2022-11-24 09:44 UTC, Rickk137 approved these changes

2022-11-24 11:18 UTC, LunaSov approved these changes

2022-11-24 11:19 UTC, merged